# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  adobe-acrobat-sign-connector:
    host: api.eu2.adobesign.com
    returnPage: /designer/page/adobe-acrobat-sign-connector$1/signatureReturn.jsp
    baseUri: https://api.eu2.adobesign.com/oauth/v2
    authenticationUri: https://secure.eu2.adobesign.com/public/oauth/v2
    clientId: ''
    clientSecret: ''
    permissions: user_read:account user_write:account user_login:account agreement_read:account
      agreement_write:account agreement_send:account widget_read:account widget_write:account
      library_read:account library_write:account workflow_read:account workflow_write:account
    oauthToken: default-value
    accessToken: default-value
    integrationKey: ''
