/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse2001
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class InlineResponse2001 {
  /**
   * Type of account to which the user belongs (null if no account)
   */
  public enum AccountTypeEnum {
    FREE("FREE"),
    PRO("PRO"),
    TEAM("TEAM"),
    TEAM_TRIAL("TEAM_TRIAL"),
    ENTERPRISE("ENTERPRISE"),
    ENTERPRISE_TRIAL("ENTERPRISE_TRIAL"),
    GLOBAL("GLOBAL"),
    GLOBAL_TRIAL("GLOBAL_TRIAL");

    private String value;

    AccountTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AccountTypeEnum fromValue(String input) {
      for (AccountTypeEnum b : AccountTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("accountType")
  private AccountTypeEnum accountType = null;

  @JsonProperty("company")
  private String company = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("initials")
  private String initials = null;

  @JsonProperty("isAccountAdmin")
  private Boolean isAccountAdmin = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("phone")
  private String phone = null;

  /**
   * Status of the user
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE"),
    CREATED("CREATED"),
    UNVERIFIED("UNVERIFIED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("title")
  private String title = null;

  public InlineResponse2001 accountType(AccountTypeEnum accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Type of account to which the user belongs (null if no account)
   * @return accountType
  **/
  public AccountTypeEnum getAccountType() {
    return accountType;
  }

  public void setAccountType(AccountTypeEnum accountType) {
    this.accountType = accountType;
  }

  public InlineResponse2001 company(String company) {
    this.company = company;
    return this;
  }

   /**
   * The name of company of the user
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public InlineResponse2001 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the user
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InlineResponse2001 firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the user
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public InlineResponse2001 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier of the user resource for REST APIs as issued by Sign.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse2001 initials(String initials) {
    this.initials = initials;
    return this;
  }

   /**
   * The initials of the user
   * @return initials
  **/
  public String getInitials() {
    return initials;
  }

  public void setInitials(String initials) {
    this.initials = initials;
  }

  public InlineResponse2001 isAccountAdmin(Boolean isAccountAdmin) {
    this.isAccountAdmin = isAccountAdmin;
    return this;
  }

   /**
   * True if the user is account admin
   * @return isAccountAdmin
  **/
  public Boolean isIsAccountAdmin() {
    return isAccountAdmin;
  }

  public void setIsAccountAdmin(Boolean isAccountAdmin) {
    this.isAccountAdmin = isAccountAdmin;
  }

  public InlineResponse2001 lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the user
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public InlineResponse2001 locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * The UI locale of the user
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public InlineResponse2001 phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * The phone number of the user
   * @return phone
  **/
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public InlineResponse2001 status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the user
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public InlineResponse2001 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The job title of the user
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.accountType, inlineResponse2001.accountType) &&
        Objects.equals(this.company, inlineResponse2001.company) &&
        Objects.equals(this.email, inlineResponse2001.email) &&
        Objects.equals(this.firstName, inlineResponse2001.firstName) &&
        Objects.equals(this.id, inlineResponse2001.id) &&
        Objects.equals(this.initials, inlineResponse2001.initials) &&
        Objects.equals(this.isAccountAdmin, inlineResponse2001.isAccountAdmin) &&
        Objects.equals(this.lastName, inlineResponse2001.lastName) &&
        Objects.equals(this.locale, inlineResponse2001.locale) &&
        Objects.equals(this.phone, inlineResponse2001.phone) &&
        Objects.equals(this.status, inlineResponse2001.status) &&
        Objects.equals(this.title, inlineResponse2001.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountType, company, email, firstName, id, initials, isAccountAdmin, lastName, locale, phone, status, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    initials: ").append(toIndentedString(initials)).append("\n");
    sb.append("    isAccountAdmin: ").append(toIndentedString(isAccountAdmin)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
