/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.UserViewResponseUserViewList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2004
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class InlineResponse2004 {
  @JsonProperty("userViewList")
  private List<UserViewResponseUserViewList> userViewList = new ArrayList<>();

  public InlineResponse2004 userViewList(List<UserViewResponseUserViewList> userViewList) {
    this.userViewList = userViewList;
    return this;
  }

  public InlineResponse2004 addUserViewListItem(UserViewResponseUserViewList userViewListItem) {
    this.userViewList.add(userViewListItem);
    return this;
  }

   /**
   * List of user views
   * @return userViewList
  **/
  public List<UserViewResponseUserViewList> getUserViewList() {
    return userViewList;
  }

  public void setUserViewList(List<UserViewResponseUserViewList> userViewList) {
    this.userViewList = userViewList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.userViewList, inlineResponse2004.userViewList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userViewList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    userViewList: ").append(toIndentedString(userViewList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
