/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.UsersInfoPage;
import api.rest.v6.client.UsersInfoUserInfoList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * UsersInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class UsersInfo {
  @JsonProperty("page")
  private UsersInfoPage page = null;

  @JsonProperty("userInfoList")
  private List<UsersInfoUserInfoList> userInfoList = new ArrayList<>();

  public UsersInfo page(UsersInfoPage page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  public UsersInfoPage getPage() {
    return page;
  }

  public void setPage(UsersInfoPage page) {
    this.page = page;
  }

  public UsersInfo userInfoList(List<UsersInfoUserInfoList> userInfoList) {
    this.userInfoList = userInfoList;
    return this;
  }

  public UsersInfo addUserInfoListItem(UsersInfoUserInfoList userInfoListItem) {
    this.userInfoList.add(userInfoListItem);
    return this;
  }

   /**
   * The list of users in the account.
   * @return userInfoList
  **/
  public List<UsersInfoUserInfoList> getUserInfoList() {
    return userInfoList;
  }

  public void setUserInfoList(List<UsersInfoUserInfoList> userInfoList) {
    this.userInfoList = userInfoList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersInfo usersInfo = (UsersInfo) o;
    return Objects.equals(this.page, usersInfo.page) &&
        Objects.equals(this.userInfoList, usersInfo.userInfoList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, userInfoList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersInfo {\n");
    
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    userInfoList: ").append(toIndentedString(userInfoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
