/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersInfoUserInfoList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class UsersInfoUserInfoList {
  @JsonProperty("company")
  private String company = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("isAccountAdmin")
  private Boolean isAccountAdmin = null;

  @JsonProperty("lastName")
  private String lastName = null;

  public UsersInfoUserInfoList company(String company) {
    this.company = company;
    return this;
  }

   /**
   * The name of company of the user
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public UsersInfoUserInfoList email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the user
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UsersInfoUserInfoList firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the user
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UsersInfoUserInfoList id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier of the user resource for REST APIs as issued by Sign.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UsersInfoUserInfoList isAccountAdmin(Boolean isAccountAdmin) {
    this.isAccountAdmin = isAccountAdmin;
    return this;
  }

   /**
   * True if user is account admin
   * @return isAccountAdmin
  **/
  public Boolean isIsAccountAdmin() {
    return isAccountAdmin;
  }

  public void setIsAccountAdmin(Boolean isAccountAdmin) {
    this.isAccountAdmin = isAccountAdmin;
  }

  public UsersInfoUserInfoList lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the user
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersInfoUserInfoList usersInfoUserInfoList = (UsersInfoUserInfoList) o;
    return Objects.equals(this.company, usersInfoUserInfoList.company) &&
        Objects.equals(this.email, usersInfoUserInfoList.email) &&
        Objects.equals(this.firstName, usersInfoUserInfoList.firstName) &&
        Objects.equals(this.id, usersInfoUserInfoList.id) &&
        Objects.equals(this.isAccountAdmin, usersInfoUserInfoList.isAccountAdmin) &&
        Objects.equals(this.lastName, usersInfoUserInfoList.lastName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, email, firstName, id, isAccountAdmin, lastName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersInfoUserInfoList {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isAccountAdmin: ").append(toIndentedString(isAccountAdmin)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
