/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserStatusUpdateResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class UserStatusUpdateResponse {
  /**
   * The result of the attempt to activate or deactivate the user
   */
  public enum CodeEnum {
    ALREADY_ACTIVE("ALREADY_ACTIVE"),
    ALREADY_INACTIVE("ALREADY_INACTIVE"),
    OK("OK"),
    RESET_PASSWORD_WORKFLOW_INITIATED("RESET_PASSWORD_WORKFLOW_INITIATED"),
    SET_PASSWORD_WORKFLOW_INITIATED("SET_PASSWORD_WORKFLOW_INITIATED");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CodeEnum fromValue(String input) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("code")
  private CodeEnum code = null;

  @JsonProperty("message")
  private String message = null;

  /**
   * A status value showing the result of this operation
   */
  public enum StateEnum {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE"),
    CREATED("CREATED"),
    PENDING("PENDING"),
    UNVERIFIED("UNVERIFIED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("state")
  private StateEnum state = null;

  public UserStatusUpdateResponse code(CodeEnum code) {
    this.code = code;
    return this;
  }

   /**
   * The result of the attempt to activate or deactivate the user
   * @return code
  **/
  public CodeEnum getCode() {
    return code;
  }

  public void setCode(CodeEnum code) {
    this.code = code;
  }

  public UserStatusUpdateResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * String result message if there was no error
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public UserStatusUpdateResponse state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * A status value showing the result of this operation
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserStatusUpdateResponse userStatusUpdateResponse = (UserStatusUpdateResponse) o;
    return Objects.equals(this.code, userStatusUpdateResponse.code) &&
        Objects.equals(this.message, userStatusUpdateResponse.message) &&
        Objects.equals(this.state, userStatusUpdateResponse.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserStatusUpdateResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
