/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
/**
 * UserView
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class UserView {
  @JsonProperty("embeddedCode")
  private String embeddedCode = null;

  @JsonProperty("expiration")
  private LocalDate expiration = null;

  /**
   * Name of the requested user view
   */
  public enum NameEnum {
    MANAGE("MANAGE"),
    ACCOUNT_SETTINGS("ACCOUNT_SETTINGS"),
    USER_PROFILE("USER_PROFILE"),
    ALL("ALL");

    private String value;

    NameEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static NameEnum fromValue(String input) {
      for (NameEnum b : NameEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("name")
  private NameEnum name = null;

  @JsonProperty("url")
  private String url = null;

  public UserView embeddedCode(String embeddedCode) {
    this.embeddedCode = embeddedCode;
    return this;
  }

   /**
   * Embedded code of url of resource 
   * @return embeddedCode
  **/
  public String getEmbeddedCode() {
    return embeddedCode;
  }

  public void setEmbeddedCode(String embeddedCode) {
    this.embeddedCode = embeddedCode;
  }

  public UserView expiration(LocalDate expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Expiration of user url 
   * @return expiration
  **/
  public LocalDate getExpiration() {
    return expiration;
  }

  public void setExpiration(LocalDate expiration) {
    this.expiration = expiration;
  }

  public UserView name(NameEnum name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the requested user view
   * @return name
  **/
  public NameEnum getName() {
    return name;
  }

  public void setName(NameEnum name) {
    this.name = name;
  }

  public UserView url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url of resource location
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserView userView = (UserView) o;
    return Objects.equals(this.embeddedCode, userView.embeddedCode) &&
        Objects.equals(this.expiration, userView.expiration) &&
        Objects.equals(this.name, userView.name) &&
        Objects.equals(this.url, userView.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(embeddedCode, expiration, name, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserView {\n");
    
    sb.append("    embeddedCode: ").append(toIndentedString(embeddedCode)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
