/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.UsersuserIdviewsCommonViewConfiguration;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserViewInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class UserViewInfo {
  @JsonProperty("commonViewConfiguration")
  private UsersuserIdviewsCommonViewConfiguration commonViewConfiguration = null;

  /**
   * Name of the requested user view
   */
  public enum NameEnum {
    MANAGE("MANAGE"),
    ACCOUNT_SETTINGS("ACCOUNT_SETTINGS"),
    USER_PROFILE("USER_PROFILE"),
    ALL("ALL");

    private String value;

    NameEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static NameEnum fromValue(String input) {
      for (NameEnum b : NameEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("name")
  private NameEnum name = null;

  public UserViewInfo commonViewConfiguration(UsersuserIdviewsCommonViewConfiguration commonViewConfiguration) {
    this.commonViewConfiguration = commonViewConfiguration;
    return this;
  }

   /**
   * Get commonViewConfiguration
   * @return commonViewConfiguration
  **/
  public UsersuserIdviewsCommonViewConfiguration getCommonViewConfiguration() {
    return commonViewConfiguration;
  }

  public void setCommonViewConfiguration(UsersuserIdviewsCommonViewConfiguration commonViewConfiguration) {
    this.commonViewConfiguration = commonViewConfiguration;
  }

  public UserViewInfo name(NameEnum name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the requested user view
   * @return name
  **/
  public NameEnum getName() {
    return name;
  }

  public void setName(NameEnum name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserViewInfo userViewInfo = (UserViewInfo) o;
    return Objects.equals(this.commonViewConfiguration, userViewInfo.commonViewConfiguration) &&
        Objects.equals(this.name, userViewInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonViewConfiguration, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserViewInfo {\n");
    
    sb.append("    commonViewConfiguration: ").append(toIndentedString(commonViewConfiguration)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
