/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersuserIdgroupsGroupInfoList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-20T14:44:07.024613500+01:00[Europe/Vienna]")
public class UsersuserIdgroupsGroupInfoList {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("isGroupAdmin")
  private Boolean isGroupAdmin = null;

  @JsonProperty("name")
  private String name = null;

  public UsersuserIdgroupsGroupInfoList id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the group
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UsersuserIdgroupsGroupInfoList isGroupAdmin(Boolean isGroupAdmin) {
    this.isGroupAdmin = isGroupAdmin;
    return this;
  }

   /**
   * True if user is group admin.
   * @return isGroupAdmin
  **/
  public Boolean isIsGroupAdmin() {
    return isGroupAdmin;
  }

  public void setIsGroupAdmin(Boolean isGroupAdmin) {
    this.isGroupAdmin = isGroupAdmin;
  }

  public UsersuserIdgroupsGroupInfoList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the group. This will be ignored as part of PUT call.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersuserIdgroupsGroupInfoList usersuserIdgroupsGroupInfoList = (UsersuserIdgroupsGroupInfoList) o;
    return Objects.equals(this.id, usersuserIdgroupsGroupInfoList.id) &&
        Objects.equals(this.isGroupAdmin, usersuserIdgroupsGroupInfoList.isGroupAdmin) &&
        Objects.equals(this.name, usersuserIdgroupsGroupInfoList.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, isGroupAdmin, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersuserIdgroupsGroupInfoList {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isGroupAdmin: ").append(toIndentedString(isGroupAdmin)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
