/*
 * secure.eu2.echosign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.File;
/**
 * TransientDocumentsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-16T07:38:44.543607900+02:00[Europe/Vienna]")
public class TransientDocumentsBody {
  @JsonProperty("File-Name")
  private String fileName = null;

  @JsonProperty("Mime-Type")
  private String mimeType = null;

  @JsonProperty("File")
  private File file = null;

  public TransientDocumentsBody fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * A name for the document being uploaded. Maximum number of characters in the name is restricted to 255.
   * @return fileName
  **/
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public TransientDocumentsBody mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * The mime type of the document being uploaded. If not specified here then mime type is picked up from the file object. If mime type is not present there either then mime type is inferred from file name extension.
   * @return mimeType
  **/
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public TransientDocumentsBody file(File file) {
    this.file = file;
    return this;
  }

   /**
   * The file part of the multipart request for document upload. You can upload only one file at a time.
   * @return file
  **/
  public File getFile() {
    return file;
  }

  public void setFile(File file) {
    this.file = file;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransientDocumentsBody transientDocumentsBody = (TransientDocumentsBody) o;
    return Objects.equals(this.fileName, transientDocumentsBody.fileName) &&
        Objects.equals(this.mimeType, transientDocumentsBody.mimeType) &&
        Objects.equals(this.file, transientDocumentsBody.file);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, mimeType, Objects.hashCode(file));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransientDocumentsBody {\n");
    
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
