# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
#  myVariable: value
  adobe-sign-connector:
    host: api.eu2.echosign.com
    integrationKey: 
    returnPage: http://localhost:8081/designer/page/adobe-esign-connector$1/signatureReturn.jsp