/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AccountSharerInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AccountSharerInfo {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("fullName")
  private String fullName = null;

  /**
   * Gets or Sets permissions
   */
  public enum PermissionsEnum {
    VIEW("VIEW"),
    SEND("SEND"),
    MODIFY("MODIFY");

    private String value;

    PermissionsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PermissionsEnum fromValue(String input) {
      for (PermissionsEnum b : PermissionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("permissions")
  private List<PermissionsEnum> permissions = new ArrayList<>();

  @JsonProperty("userId")
  private String userId = null;

  public AccountSharerInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the user
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AccountSharerInfo fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Full name of this account sharer.
   * @return fullName
  **/
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public AccountSharerInfo permissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
    return this;
  }

  public AccountSharerInfo addPermissionsItem(PermissionsEnum permissionsItem) {
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * A list of permissions given for this account sharing.
   * @return permissions
  **/
  public List<PermissionsEnum> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
  }

  public AccountSharerInfo userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * A unique identifier of the user resource for REST APIs as issued by Acrobat Sign.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountSharerInfo accountSharerInfo = (AccountSharerInfo) o;
    return Objects.equals(this.email, accountSharerInfo.email) &&
        Objects.equals(this.fullName, accountSharerInfo.fullName) &&
        Objects.equals(this.permissions, accountSharerInfo.permissions) &&
        Objects.equals(this.userId, accountSharerInfo.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, fullName, permissions, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountSharerInfo {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
