/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AgreementCcInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementCcInfo {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("label")
  private String label = null;

  @JsonProperty("visiblePages")
  private List<String> visiblePages = null;

  public AgreementCcInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the CC participant of the agreement
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AgreementCcInfo label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Label of the CC list as returned in workflow description
   * @return label
  **/
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public AgreementCcInfo visiblePages(List<String> visiblePages) {
    this.visiblePages = visiblePages;
    return this;
  }

  public AgreementCcInfo addVisiblePagesItem(String visiblePagesItem) {
    if (this.visiblePages == null) {
      this.visiblePages = new ArrayList<>();
    }
    this.visiblePages.add(visiblePagesItem);
    return this;
  }

   /**
   * When you enable limited document visibility (documentVisibilityEnabled), you can specify which file (fileInfo) should be made visible to which specific participant set.&lt;br&gt;Specify one or more label values of a fileInfos element.&lt;br&gt;Each signer participant sets must contain at least one required signature field in at least one visible file included in this API call; if not a page with a signature field is automatically appended for any missing participant sets. If there is a possibility that one or more participant sets do not have a required signature field in the files included in the API call, all signer participant sets should include a special index value of &#x27;0&#x27; to make this automatically appended signature page visible to the signer. Not doing so may result in an error. For all other roles, you may omit this value to exclude this page.
   * @return visiblePages
  **/
  public List<String> getVisiblePages() {
    return visiblePages;
  }

  public void setVisiblePages(List<String> visiblePages) {
    this.visiblePages = visiblePages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementCcInfo agreementCcInfo = (AgreementCcInfo) o;
    return Objects.equals(this.email, agreementCcInfo.email) &&
        Objects.equals(this.label, agreementCcInfo.label) &&
        Objects.equals(this.visiblePages, agreementCcInfo.visiblePages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, label, visiblePages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementCcInfo {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    visiblePages: ").append(toIndentedString(visiblePages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
