/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementEventDigitalSignatureInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementEventDigitalSignatureInfo {
  @JsonProperty("certificateIssuer")
  private String certificateIssuer = null;

  @JsonProperty("cloudProviderIp")
  private String cloudProviderIp = null;

  @JsonProperty("cloudProviderName")
  private String cloudProviderName = null;

  @JsonProperty("cloudProviderUrl")
  private String cloudProviderUrl = null;

  @JsonProperty("company")
  private String company = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("name")
  private String name = null;

  public AgreementEventDigitalSignatureInfo certificateIssuer(String certificateIssuer) {
    this.certificateIssuer = certificateIssuer;
    return this;
  }

   /**
   * Certificate Issuer for digital signing
   * @return certificateIssuer
  **/
  public String getCertificateIssuer() {
    return certificateIssuer;
  }

  public void setCertificateIssuer(String certificateIssuer) {
    this.certificateIssuer = certificateIssuer;
  }

  public AgreementEventDigitalSignatureInfo cloudProviderIp(String cloudProviderIp) {
    this.cloudProviderIp = cloudProviderIp;
    return this;
  }

   /**
   * Cloud Provider IP for digital signing
   * @return cloudProviderIp
  **/
  public String getCloudProviderIp() {
    return cloudProviderIp;
  }

  public void setCloudProviderIp(String cloudProviderIp) {
    this.cloudProviderIp = cloudProviderIp;
  }

  public AgreementEventDigitalSignatureInfo cloudProviderName(String cloudProviderName) {
    this.cloudProviderName = cloudProviderName;
    return this;
  }

   /**
   * Cloud Provider Name for digital signing
   * @return cloudProviderName
  **/
  public String getCloudProviderName() {
    return cloudProviderName;
  }

  public void setCloudProviderName(String cloudProviderName) {
    this.cloudProviderName = cloudProviderName;
  }

  public AgreementEventDigitalSignatureInfo cloudProviderUrl(String cloudProviderUrl) {
    this.cloudProviderUrl = cloudProviderUrl;
    return this;
  }

   /**
   * Cloud Provider URL for digital signing
   * @return cloudProviderUrl
  **/
  public String getCloudProviderUrl() {
    return cloudProviderUrl;
  }

  public void setCloudProviderUrl(String cloudProviderUrl) {
    this.cloudProviderUrl = cloudProviderUrl;
  }

  public AgreementEventDigitalSignatureInfo company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Company name captured during digital signing
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public AgreementEventDigitalSignatureInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email captured during digital signing
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AgreementEventDigitalSignatureInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name captured during digital signing
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementEventDigitalSignatureInfo agreementEventDigitalSignatureInfo = (AgreementEventDigitalSignatureInfo) o;
    return Objects.equals(this.certificateIssuer, agreementEventDigitalSignatureInfo.certificateIssuer) &&
        Objects.equals(this.cloudProviderIp, agreementEventDigitalSignatureInfo.cloudProviderIp) &&
        Objects.equals(this.cloudProviderName, agreementEventDigitalSignatureInfo.cloudProviderName) &&
        Objects.equals(this.cloudProviderUrl, agreementEventDigitalSignatureInfo.cloudProviderUrl) &&
        Objects.equals(this.company, agreementEventDigitalSignatureInfo.company) &&
        Objects.equals(this.email, agreementEventDigitalSignatureInfo.email) &&
        Objects.equals(this.name, agreementEventDigitalSignatureInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateIssuer, cloudProviderIp, cloudProviderName, cloudProviderUrl, company, email, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementEventDigitalSignatureInfo {\n");
    
    sb.append("    certificateIssuer: ").append(toIndentedString(certificateIssuer)).append("\n");
    sb.append("    cloudProviderIp: ").append(toIndentedString(cloudProviderIp)).append("\n");
    sb.append("    cloudProviderName: ").append(toIndentedString(cloudProviderName)).append("\n");
    sb.append("    cloudProviderUrl: ").append(toIndentedString(cloudProviderUrl)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
