/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsFormFieldDescriptionHyperlinkDocumentLocation;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Hyperlink-specific data for hyperlink form fields
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsFormFieldDescriptionHyperlink {
  @JsonProperty("documentLocation")
  private AgreementsFormFieldDescriptionHyperlinkDocumentLocation documentLocation = null;

  /**
   * Type of link in an agreement.
   */
  public enum LinkTypeEnum {
    INTERNAL("INTERNAL"),
    EXTERNAL("EXTERNAL"),
    FROM_TEXT("FROM_TEXT");

    private String value;

    LinkTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LinkTypeEnum fromValue(String input) {
      for (LinkTypeEnum b : LinkTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("linkType")
  private LinkTypeEnum linkType = null;

  @JsonProperty("url")
  private String url = null;

  public AgreementsFormFieldDescriptionHyperlink documentLocation(AgreementsFormFieldDescriptionHyperlinkDocumentLocation documentLocation) {
    this.documentLocation = documentLocation;
    return this;
  }

   /**
   * Get documentLocation
   * @return documentLocation
  **/
  public AgreementsFormFieldDescriptionHyperlinkDocumentLocation getDocumentLocation() {
    return documentLocation;
  }

  public void setDocumentLocation(AgreementsFormFieldDescriptionHyperlinkDocumentLocation documentLocation) {
    this.documentLocation = documentLocation;
  }

  public AgreementsFormFieldDescriptionHyperlink linkType(LinkTypeEnum linkType) {
    this.linkType = linkType;
    return this;
  }

   /**
   * Type of link in an agreement.
   * @return linkType
  **/
  public LinkTypeEnum getLinkType() {
    return linkType;
  }

  public void setLinkType(LinkTypeEnum linkType) {
    this.linkType = linkType;
  }

  public AgreementsFormFieldDescriptionHyperlink url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL, in case of EXTERNAL type link
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsFormFieldDescriptionHyperlink agreementsFormFieldDescriptionHyperlink = (AgreementsFormFieldDescriptionHyperlink) o;
    return Objects.equals(this.documentLocation, agreementsFormFieldDescriptionHyperlink.documentLocation) &&
        Objects.equals(this.linkType, agreementsFormFieldDescriptionHyperlink.linkType) &&
        Objects.equals(this.url, agreementsFormFieldDescriptionHyperlink.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentLocation, linkType, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsFormFieldDescriptionHyperlink {\n");
    
    sb.append("    documentLocation: ").append(toIndentedString(documentLocation)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
