/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementCreationInfoParticipantSetsInfo;
import api.rest.v6.client.AgreementsAgreementSettingsInfo;
import api.rest.v6.client.AgreementsCcs;
import api.rest.v6.client.AgreementsDeviceInfo;
import api.rest.v6.client.AgreementsEmailOption;
import api.rest.v6.client.AgreementsExternalId;
import api.rest.v6.client.AgreementsFileInfos;
import api.rest.v6.client.AgreementsFormFieldGenerators;
import api.rest.v6.client.AgreementsMergeFieldInfo;
import api.rest.v6.client.AgreementsNotaryInfo;
import api.rest.v6.client.AgreementsPostSignOption;
import api.rest.v6.client.AgreementsSecurityOption1;
import api.rest.v6.client.AgreementsVaultingInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
/**
 * AgreementInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementInfo {
  @JsonProperty("agreementSettingsInfo")
  private AgreementsAgreementSettingsInfo agreementSettingsInfo = null;

  @JsonProperty("ccs")
  private List<AgreementsCcs> ccs = null;

  @JsonProperty("createdDate")
  private LocalDate createdDate = null;

  @JsonProperty("deviceInfo")
  private AgreementsDeviceInfo deviceInfo = null;

  @JsonProperty("documentRetentionAppliedDate")
  private LocalDate documentRetentionAppliedDate = null;

  @JsonProperty("documentVisibilityEnabled")
  private Boolean documentVisibilityEnabled = null;

  @JsonProperty("emailOption")
  private AgreementsEmailOption emailOption = null;

  @JsonProperty("expirationTime")
  private LocalDate expirationTime = null;

  @JsonProperty("externalId")
  private AgreementsExternalId externalId = null;

  @JsonProperty("fileInfos")
  private List<AgreementsFileInfos> fileInfos = new ArrayList<>();

  @JsonProperty("firstReminderDelay")
  private Integer firstReminderDelay = null;

  @JsonProperty("formFieldGenerators")
  private List<AgreementsFormFieldGenerators> formFieldGenerators = null;

  @JsonProperty("formFieldLayerTemplates")
  private List<AgreementsFileInfos> formFieldLayerTemplates = null;

  @JsonProperty("groupId")
  private String groupId = null;

  @JsonProperty("hasFormFieldData")
  private Boolean hasFormFieldData = null;

  @JsonProperty("hasSignerIdentityReport")
  private Boolean hasSignerIdentityReport = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("isDocumentRetentionApplied")
  private Boolean isDocumentRetentionApplied = null;

  @JsonProperty("lastEventDate")
  private LocalDate lastEventDate = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("mergeFieldInfo")
  private List<AgreementsMergeFieldInfo> mergeFieldInfo = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("notaryInfo")
  private AgreementsNotaryInfo notaryInfo = null;

  @JsonProperty("parentId")
  private String parentId = null;

  @JsonProperty("participantSetsInfo")
  private List<AgreementCreationInfoParticipantSetsInfo> participantSetsInfo = new ArrayList<>();

  @JsonProperty("postSignOption")
  private AgreementsPostSignOption postSignOption = null;

  /**
   * Optional parameter that sets how often you want to send reminders to the participants. If it is not specified, the default frequency set for the account will be used. Should not be provided in offline agreement creation. If provided in PUT as a different value than the current one, an error will be thrown.
   */
  public enum ReminderFrequencyEnum {
    DAILY_UNTIL_SIGNED("DAILY_UNTIL_SIGNED"),
    WEEKDAILY_UNTIL_SIGNED("WEEKDAILY_UNTIL_SIGNED"),
    EVERY_OTHER_DAY_UNTIL_SIGNED("EVERY_OTHER_DAY_UNTIL_SIGNED"),
    EVERY_THIRD_DAY_UNTIL_SIGNED("EVERY_THIRD_DAY_UNTIL_SIGNED"),
    EVERY_FIFTH_DAY_UNTIL_SIGNED("EVERY_FIFTH_DAY_UNTIL_SIGNED"),
    WEEKLY_UNTIL_SIGNED("WEEKLY_UNTIL_SIGNED"),
    ONCE("ONCE");

    private String value;

    ReminderFrequencyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReminderFrequencyEnum fromValue(String input) {
      for (ReminderFrequencyEnum b : ReminderFrequencyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("reminderFrequency")
  private ReminderFrequencyEnum reminderFrequency = null;

  @JsonProperty("securityOption")
  private AgreementsSecurityOption1 securityOption = null;

  /**
   * Indicates the experience being used by the originator to send an agreement. &lt;br&gt;FILL_SIGN: originator is using Fill and Sign experience &lt;br&gt;SELF_SIGN: originator is using Self Signing experience &lt;br&gt;REGULAR_SEND: originator is using regular Send experience
   */
  public enum SendTypeEnum {
    FILL_SIGN("FILL_SIGN"),
    SELF_SIGN("SELF_SIGN"),
    REGULAR_SEND("REGULAR_SEND");

    private String value;

    SendTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SendTypeEnum fromValue(String input) {
      for (SendTypeEnum b : SendTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("sendType")
  private SendTypeEnum sendType = null;

  @JsonProperty("senderEmail")
  private String senderEmail = null;

  /**
   * Indicates the SenderSigns type that applies to the agreement.
   */
  public enum SenderSignsEnum {
    FIRST("FIRST"),
    LAST("LAST"),
    NEVER("NEVER"),
    APPROVE("APPROVE"),
    ARCHIVE("ARCHIVE"),
    FORWARD("FORWARD"),
    SEQUENTIAL("SEQUENTIAL"),
    DELIVER("DELIVER"),
    FILL_SIGN("FILL_SIGN"),
    SEND_ONLY_TO_SELF("SEND_ONLY_TO_SELF");

    private String value;

    SenderSignsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SenderSignsEnum fromValue(String input) {
      for (SenderSignsEnum b : SenderSignsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("senderSigns")
  private SenderSignsEnum senderSigns = null;

  /**
   * Specifies the type of signature you would like to request - written or e-signature. The possible values are &lt;br&gt; ESIGN : Agreement needs to be signed electronically &lt;br&gt;, WRITTEN : Agreement will be signed using handwritten signature and signed document will be uploaded into the system
   */
  public enum SignatureTypeEnum {
    ESIGN("ESIGN"),
    WRITTEN("WRITTEN");

    private String value;

    SignatureTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SignatureTypeEnum fromValue(String input) {
      for (SignatureTypeEnum b : SignatureTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("signatureType")
  private SignatureTypeEnum signatureType = null;

  /**
   * The state in which the agreement should land. The state field can only be provided in POST calls, will never get returned in GET /agreements/{ID} and will be ignored if provided in PUT /agreements/{ID} call. The eventual status of the agreement can be obtained from GET /agreements/ID
   */
  public enum StateEnum {
    AUTHORING("AUTHORING"),
    DRAFT("DRAFT"),
    IN_PROCESS("IN_PROCESS"),
    RESTART("RESTART");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("state")
  private StateEnum state = null;

  /**
   * This is a server generated attribute which provides the detailed status of an agreement.
   */
  public enum StatusEnum {
    OUT_FOR_SIGNATURE("OUT_FOR_SIGNATURE"),
    OUT_FOR_DELIVERY("OUT_FOR_DELIVERY"),
    OUT_FOR_ACCEPTANCE("OUT_FOR_ACCEPTANCE"),
    OUT_FOR_FORM_FILLING("OUT_FOR_FORM_FILLING"),
    OUT_FOR_APPROVAL("OUT_FOR_APPROVAL"),
    AUTHORING("AUTHORING"),
    CANCELLED("CANCELLED"),
    SIGNED("SIGNED"),
    APPROVED("APPROVED"),
    DELIVERED("DELIVERED"),
    ACCEPTED("ACCEPTED"),
    FORM_FILLED("FORM_FILLED"),
    EXPIRED("EXPIRED"),
    ARCHIVED("ARCHIVED"),
    PREFILL("PREFILL"),
    WIDGET_WAITING_FOR_VERIFICATION("WIDGET_WAITING_FOR_VERIFICATION"),
    DRAFT("DRAFT"),
    DOCUMENTS_NOT_YET_PROCESSED("DOCUMENTS_NOT_YET_PROCESSED"),
    WAITING_FOR_FAXIN("WAITING_FOR_FAXIN"),
    WAITING_FOR_VERIFICATION("WAITING_FOR_VERIFICATION"),
    WAITING_FOR_NOTARIZATION("WAITING_FOR_NOTARIZATION");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  /**
   * The kind of agreement
   */
  public enum TypeEnum {
    AGREEMENT("AGREEMENT"),
    MEGASIGN_CHILD("MEGASIGN_CHILD"),
    WIDGET_INSTANCE("WIDGET_INSTANCE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("vaultingInfo")
  private AgreementsVaultingInfo vaultingInfo = null;

  @JsonProperty("workflowId")
  private String workflowId = null;

  public AgreementInfo agreementSettingsInfo(AgreementsAgreementSettingsInfo agreementSettingsInfo) {
    this.agreementSettingsInfo = agreementSettingsInfo;
    return this;
  }

   /**
   * Get agreementSettingsInfo
   * @return agreementSettingsInfo
  **/
  public AgreementsAgreementSettingsInfo getAgreementSettingsInfo() {
    return agreementSettingsInfo;
  }

  public void setAgreementSettingsInfo(AgreementsAgreementSettingsInfo agreementSettingsInfo) {
    this.agreementSettingsInfo = agreementSettingsInfo;
  }

  public AgreementInfo ccs(List<AgreementsCcs> ccs) {
    this.ccs = ccs;
    return this;
  }

  public AgreementInfo addCcsItem(AgreementsCcs ccsItem) {
    if (this.ccs == null) {
      this.ccs = new ArrayList<>();
    }
    this.ccs.add(ccsItem);
    return this;
  }

   /**
   * A list of one or more CCs that will be copied in the agreement transaction. The CCs will each receive an email at the beginning of the transaction and also when the final document is signed. The email addresses will also receive a copy of the document, attached as a PDF file. Should not be provided in offline agreement creation.
   * @return ccs
  **/
  public List<AgreementsCcs> getCcs() {
    return ccs;
  }

  public void setCcs(List<AgreementsCcs> ccs) {
    this.ccs = ccs;
  }

  public AgreementInfo createdDate(LocalDate createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date when agreement was created. This is a server generated attributed and can not be provided in POST/PUT calls. Format would be yyyy-MM-dd&#x27;T&#x27;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
   * @return createdDate
  **/
  public LocalDate getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(LocalDate createdDate) {
    this.createdDate = createdDate;
  }

  public AgreementInfo deviceInfo(AgreementsDeviceInfo deviceInfo) {
    this.deviceInfo = deviceInfo;
    return this;
  }

   /**
   * Get deviceInfo
   * @return deviceInfo
  **/
  public AgreementsDeviceInfo getDeviceInfo() {
    return deviceInfo;
  }

  public void setDeviceInfo(AgreementsDeviceInfo deviceInfo) {
    this.deviceInfo = deviceInfo;
  }

  public AgreementInfo documentRetentionAppliedDate(LocalDate documentRetentionAppliedDate) {
    this.documentRetentionAppliedDate = documentRetentionAppliedDate;
    return this;
  }

   /**
   * Document retention applied date for this resource.  If provided in POST or PUT, it will simply be ignored.
   * @return documentRetentionAppliedDate
  **/
  public LocalDate getDocumentRetentionAppliedDate() {
    return documentRetentionAppliedDate;
  }

  public void setDocumentRetentionAppliedDate(LocalDate documentRetentionAppliedDate) {
    this.documentRetentionAppliedDate = documentRetentionAppliedDate;
  }

  public AgreementInfo documentVisibilityEnabled(Boolean documentVisibilityEnabled) {
    this.documentVisibilityEnabled = documentVisibilityEnabled;
    return this;
  }

   /**
   * If set to true, enable limited document visibility. Should not be provided in offline agreement creation.
   * @return documentVisibilityEnabled
  **/
  public Boolean isDocumentVisibilityEnabled() {
    return documentVisibilityEnabled;
  }

  public void setDocumentVisibilityEnabled(Boolean documentVisibilityEnabled) {
    this.documentVisibilityEnabled = documentVisibilityEnabled;
  }

  public AgreementInfo emailOption(AgreementsEmailOption emailOption) {
    this.emailOption = emailOption;
    return this;
  }

   /**
   * Get emailOption
   * @return emailOption
  **/
  public AgreementsEmailOption getEmailOption() {
    return emailOption;
  }

  public void setEmailOption(AgreementsEmailOption emailOption) {
    this.emailOption = emailOption;
  }

  public AgreementInfo expirationTime(LocalDate expirationTime) {
    this.expirationTime = expirationTime;
    return this;
  }

   /**
   * Time after which Agreement expires and needs to be signed before it. Format should be yyyy-MM-dd&#x27;T&#x27;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time. Should not be provided in offline agreement creation. Agreements in DRAFT and AUTHORING status do not expire. The expiration count down starts when agreement is sent.
   * @return expirationTime
  **/
  public LocalDate getExpirationTime() {
    return expirationTime;
  }

  public void setExpirationTime(LocalDate expirationTime) {
    this.expirationTime = expirationTime;
  }

  public AgreementInfo externalId(AgreementsExternalId externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  public AgreementsExternalId getExternalId() {
    return externalId;
  }

  public void setExternalId(AgreementsExternalId externalId) {
    this.externalId = externalId;
  }

  public AgreementInfo fileInfos(List<AgreementsFileInfos> fileInfos) {
    this.fileInfos = fileInfos;
    return this;
  }

  public AgreementInfo addFileInfosItem(AgreementsFileInfos fileInfosItem) {
    this.fileInfos.add(fileInfosItem);
    return this;
  }

   /**
   * A list of one or more files (or references to files) that will be sent out for signature. If more than one file is provided, they will be combined into one PDF before being sent out. Note: Only one of the four parameters in every FileInfo object must be specified
   * @return fileInfos
  **/
  public List<AgreementsFileInfos> getFileInfos() {
    return fileInfos;
  }

  public void setFileInfos(List<AgreementsFileInfos> fileInfos) {
    this.fileInfos = fileInfos;
  }

  public AgreementInfo firstReminderDelay(Integer firstReminderDelay) {
    this.firstReminderDelay = firstReminderDelay;
    return this;
  }

   /**
   * Integer which specifies the delay in hours before sending the first reminder.&lt;br&gt;This is an optional field. The minimum value allowed is 1 hour and the maximum value can’t be more than the difference of agreement creation and expiry time of the agreement in hours.&lt;br&gt;If this is not specified but the reminder frequency is specified, then the first reminder will be sent based on frequency.&lt;br&gt;i.e. if the reminder is created with frequency specified as daily, the firstReminderDelay will be 24 hours. Should not be provided in offline agreement creation.
   * @return firstReminderDelay
  **/
  public Integer getFirstReminderDelay() {
    return firstReminderDelay;
  }

  public void setFirstReminderDelay(Integer firstReminderDelay) {
    this.firstReminderDelay = firstReminderDelay;
  }

  public AgreementInfo formFieldGenerators(List<AgreementsFormFieldGenerators> formFieldGenerators) {
    this.formFieldGenerators = formFieldGenerators;
    return this;
  }

  public AgreementInfo addFormFieldGeneratorsItem(AgreementsFormFieldGenerators formFieldGeneratorsItem) {
    if (this.formFieldGenerators == null) {
      this.formFieldGenerators = new ArrayList<>();
    }
    this.formFieldGenerators.add(formFieldGeneratorsItem);
    return this;
  }

   /**
   * List of form field generators to produce form fields on the resulting agreement
   * @return formFieldGenerators
  **/
  public List<AgreementsFormFieldGenerators> getFormFieldGenerators() {
    return formFieldGenerators;
  }

  public void setFormFieldGenerators(List<AgreementsFormFieldGenerators> formFieldGenerators) {
    this.formFieldGenerators = formFieldGenerators;
  }

  public AgreementInfo formFieldLayerTemplates(List<AgreementsFileInfos> formFieldLayerTemplates) {
    this.formFieldLayerTemplates = formFieldLayerTemplates;
    return this;
  }

  public AgreementInfo addFormFieldLayerTemplatesItem(AgreementsFileInfos formFieldLayerTemplatesItem) {
    if (this.formFieldLayerTemplates == null) {
      this.formFieldLayerTemplates = new ArrayList<>();
    }
    this.formFieldLayerTemplates.add(formFieldLayerTemplatesItem);
    return this;
  }

   /**
   * Specifies the form field layer template or source of form fields to apply on the files in this transaction. If specified, the FileInfo for this parameter must refer to a form field layer template via libraryDocumentId or libraryDocumentName, or if specified via transientDocumentId or documentURL, it must be of a supported file type. Note: Only one of the four parameters in every FileInfo object must be specified
   * @return formFieldLayerTemplates
  **/
  public List<AgreementsFileInfos> getFormFieldLayerTemplates() {
    return formFieldLayerTemplates;
  }

  public void setFormFieldLayerTemplates(List<AgreementsFileInfos> formFieldLayerTemplates) {
    this.formFieldLayerTemplates = formFieldLayerTemplates;
  }

  public AgreementInfo groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * The unique identifier of the group to which the agreement belongs to. If not provided during agreement creation, primary group of the creator will be used
   * @return groupId
  **/
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public AgreementInfo hasFormFieldData(Boolean hasFormFieldData) {
    this.hasFormFieldData = hasFormFieldData;
    return this;
  }

   /**
   * True if form field data is present.  If provided in POST or PUT, it will simply be ignored.
   * @return hasFormFieldData
  **/
  public Boolean isHasFormFieldData() {
    return hasFormFieldData;
  }

  public void setHasFormFieldData(Boolean hasFormFieldData) {
    this.hasFormFieldData = hasFormFieldData;
  }

  public AgreementInfo hasSignerIdentityReport(Boolean hasSignerIdentityReport) {
    this.hasSignerIdentityReport = hasSignerIdentityReport;
    return this;
  }

   /**
   * True if agreement has signer identity report available.  If provided in POST or PUT, it will simply be ignored.
   * @return hasSignerIdentityReport
  **/
  public Boolean isHasSignerIdentityReport() {
    return hasSignerIdentityReport;
  }

  public void setHasSignerIdentityReport(Boolean hasSignerIdentityReport) {
    this.hasSignerIdentityReport = hasSignerIdentityReport;
  }

  public AgreementInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the agreement.If provided in POST, it will simply be ignored
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgreementInfo isDocumentRetentionApplied(Boolean isDocumentRetentionApplied) {
    this.isDocumentRetentionApplied = isDocumentRetentionApplied;
    return this;
  }

   /**
   * Is document retention applied for this resource.  If provided in POST or PUT, it will simply be ignored.
   * @return isDocumentRetentionApplied
  **/
  public Boolean isIsDocumentRetentionApplied() {
    return isDocumentRetentionApplied;
  }

  public void setIsDocumentRetentionApplied(Boolean isDocumentRetentionApplied) {
    this.isDocumentRetentionApplied = isDocumentRetentionApplied;
  }

  public AgreementInfo lastEventDate(LocalDate lastEventDate) {
    this.lastEventDate = lastEventDate;
    return this;
  }

   /**
   * The date of the last event that occurred for this agreement. Format would be yyyy-MM-dd&#x27;T&#x27;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
   * @return lastEventDate
  **/
  public LocalDate getLastEventDate() {
    return lastEventDate;
  }

  public void setLastEventDate(LocalDate lastEventDate) {
    this.lastEventDate = lastEventDate;
  }

  public AgreementInfo locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * The locale associated with this agreement - specifies the language for the signing page and emails, for example en_US or fr_FR. If none specified, defaults to the language configured for the agreement sender
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public AgreementInfo mergeFieldInfo(List<AgreementsMergeFieldInfo> mergeFieldInfo) {
    this.mergeFieldInfo = mergeFieldInfo;
    return this;
  }

  public AgreementInfo addMergeFieldInfoItem(AgreementsMergeFieldInfo mergeFieldInfoItem) {
    if (this.mergeFieldInfo == null) {
      this.mergeFieldInfo = new ArrayList<>();
    }
    this.mergeFieldInfo.add(mergeFieldInfoItem);
    return this;
  }

   /**
   * Optional default values for fields to merge into the document. The values will be presented to the signers for editable fields; for read-only fields the provided values will not be editable during the signing process.
   * @return mergeFieldInfo
  **/
  public List<AgreementsMergeFieldInfo> getMergeFieldInfo() {
    return mergeFieldInfo;
  }

  public void setMergeFieldInfo(List<AgreementsMergeFieldInfo> mergeFieldInfo) {
    this.mergeFieldInfo = mergeFieldInfo;
  }

  public AgreementInfo message(String message) {
    this.message = message;
    return this;
  }

   /**
   * An optional message to the participants, describing what is being sent or why their signature is required
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public AgreementInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the agreement that will be used to identify it, in emails, website and other places
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AgreementInfo notaryInfo(AgreementsNotaryInfo notaryInfo) {
    this.notaryInfo = notaryInfo;
    return this;
  }

   /**
   * Get notaryInfo
   * @return notaryInfo
  **/
  public AgreementsNotaryInfo getNotaryInfo() {
    return notaryInfo;
  }

  public void setNotaryInfo(AgreementsNotaryInfo notaryInfo) {
    this.notaryInfo = notaryInfo;
  }

  public AgreementInfo parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * The parent id of a bulk send child *OR* the originating id of a web form agreement instance
   * @return parentId
  **/
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public AgreementInfo participantSetsInfo(List<AgreementCreationInfoParticipantSetsInfo> participantSetsInfo) {
    this.participantSetsInfo = participantSetsInfo;
    return this;
  }

  public AgreementInfo addParticipantSetsInfoItem(AgreementCreationInfoParticipantSetsInfo participantSetsInfoItem) {
    this.participantSetsInfo.add(participantSetsInfoItem);
    return this;
  }

   /**
   * A list of one or more participant set. A participant set may have one or more participant. If any member of the participant set takes the action that has been assigned to the set(Sign/Approve/Acknowledge etc), the action is considered as the action taken by whole participation set. For regular (non-Send in Bulk) documents, there is no limit on the number of electronic signatures in a single document. Written signatures are limited to four per document
   * @return participantSetsInfo
  **/
  public List<AgreementCreationInfoParticipantSetsInfo> getParticipantSetsInfo() {
    return participantSetsInfo;
  }

  public void setParticipantSetsInfo(List<AgreementCreationInfoParticipantSetsInfo> participantSetsInfo) {
    this.participantSetsInfo = participantSetsInfo;
  }

  public AgreementInfo postSignOption(AgreementsPostSignOption postSignOption) {
    this.postSignOption = postSignOption;
    return this;
  }

   /**
   * Get postSignOption
   * @return postSignOption
  **/
  public AgreementsPostSignOption getPostSignOption() {
    return postSignOption;
  }

  public void setPostSignOption(AgreementsPostSignOption postSignOption) {
    this.postSignOption = postSignOption;
  }

  public AgreementInfo reminderFrequency(ReminderFrequencyEnum reminderFrequency) {
    this.reminderFrequency = reminderFrequency;
    return this;
  }

   /**
   * Optional parameter that sets how often you want to send reminders to the participants. If it is not specified, the default frequency set for the account will be used. Should not be provided in offline agreement creation. If provided in PUT as a different value than the current one, an error will be thrown.
   * @return reminderFrequency
  **/
  public ReminderFrequencyEnum getReminderFrequency() {
    return reminderFrequency;
  }

  public void setReminderFrequency(ReminderFrequencyEnum reminderFrequency) {
    this.reminderFrequency = reminderFrequency;
  }

  public AgreementInfo securityOption(AgreementsSecurityOption1 securityOption) {
    this.securityOption = securityOption;
    return this;
  }

   /**
   * Get securityOption
   * @return securityOption
  **/
  public AgreementsSecurityOption1 getSecurityOption() {
    return securityOption;
  }

  public void setSecurityOption(AgreementsSecurityOption1 securityOption) {
    this.securityOption = securityOption;
  }

  public AgreementInfo sendType(SendTypeEnum sendType) {
    this.sendType = sendType;
    return this;
  }

   /**
   * Indicates the experience being used by the originator to send an agreement. &lt;br&gt;FILL_SIGN: originator is using Fill and Sign experience &lt;br&gt;SELF_SIGN: originator is using Self Signing experience &lt;br&gt;REGULAR_SEND: originator is using regular Send experience
   * @return sendType
  **/
  public SendTypeEnum getSendType() {
    return sendType;
  }

  public void setSendType(SendTypeEnum sendType) {
    this.sendType = sendType;
  }

  public AgreementInfo senderEmail(String senderEmail) {
    this.senderEmail = senderEmail;
    return this;
  }

   /**
   * Email of agreement sender. Only provided in GET. Can not be provided in POST/PUT request. If provided in POST/PUT, it will be ignored
   * @return senderEmail
  **/
  public String getSenderEmail() {
    return senderEmail;
  }

  public void setSenderEmail(String senderEmail) {
    this.senderEmail = senderEmail;
  }

  public AgreementInfo senderSigns(SenderSignsEnum senderSigns) {
    this.senderSigns = senderSigns;
    return this;
  }

   /**
   * Indicates the SenderSigns type that applies to the agreement.
   * @return senderSigns
  **/
  public SenderSignsEnum getSenderSigns() {
    return senderSigns;
  }

  public void setSenderSigns(SenderSignsEnum senderSigns) {
    this.senderSigns = senderSigns;
  }

  public AgreementInfo signatureType(SignatureTypeEnum signatureType) {
    this.signatureType = signatureType;
    return this;
  }

   /**
   * Specifies the type of signature you would like to request - written or e-signature. The possible values are &lt;br&gt; ESIGN : Agreement needs to be signed electronically &lt;br&gt;, WRITTEN : Agreement will be signed using handwritten signature and signed document will be uploaded into the system
   * @return signatureType
  **/
  public SignatureTypeEnum getSignatureType() {
    return signatureType;
  }

  public void setSignatureType(SignatureTypeEnum signatureType) {
    this.signatureType = signatureType;
  }

  public AgreementInfo state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * The state in which the agreement should land. The state field can only be provided in POST calls, will never get returned in GET /agreements/{ID} and will be ignored if provided in PUT /agreements/{ID} call. The eventual status of the agreement can be obtained from GET /agreements/ID
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public AgreementInfo status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * This is a server generated attribute which provides the detailed status of an agreement.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AgreementInfo type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The kind of agreement
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AgreementInfo vaultingInfo(AgreementsVaultingInfo vaultingInfo) {
    this.vaultingInfo = vaultingInfo;
    return this;
  }

   /**
   * Get vaultingInfo
   * @return vaultingInfo
  **/
  public AgreementsVaultingInfo getVaultingInfo() {
    return vaultingInfo;
  }

  public void setVaultingInfo(AgreementsVaultingInfo vaultingInfo) {
    this.vaultingInfo = vaultingInfo;
  }

  public AgreementInfo workflowId(String workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * The identifier of custom workflow which defines the routing path of an agreement. Should not be provided in offline agreement creation.
   * @return workflowId
  **/
  public String getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(String workflowId) {
    this.workflowId = workflowId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementInfo agreementInfo = (AgreementInfo) o;
    return Objects.equals(this.agreementSettingsInfo, agreementInfo.agreementSettingsInfo) &&
        Objects.equals(this.ccs, agreementInfo.ccs) &&
        Objects.equals(this.createdDate, agreementInfo.createdDate) &&
        Objects.equals(this.deviceInfo, agreementInfo.deviceInfo) &&
        Objects.equals(this.documentRetentionAppliedDate, agreementInfo.documentRetentionAppliedDate) &&
        Objects.equals(this.documentVisibilityEnabled, agreementInfo.documentVisibilityEnabled) &&
        Objects.equals(this.emailOption, agreementInfo.emailOption) &&
        Objects.equals(this.expirationTime, agreementInfo.expirationTime) &&
        Objects.equals(this.externalId, agreementInfo.externalId) &&
        Objects.equals(this.fileInfos, agreementInfo.fileInfos) &&
        Objects.equals(this.firstReminderDelay, agreementInfo.firstReminderDelay) &&
        Objects.equals(this.formFieldGenerators, agreementInfo.formFieldGenerators) &&
        Objects.equals(this.formFieldLayerTemplates, agreementInfo.formFieldLayerTemplates) &&
        Objects.equals(this.groupId, agreementInfo.groupId) &&
        Objects.equals(this.hasFormFieldData, agreementInfo.hasFormFieldData) &&
        Objects.equals(this.hasSignerIdentityReport, agreementInfo.hasSignerIdentityReport) &&
        Objects.equals(this.id, agreementInfo.id) &&
        Objects.equals(this.isDocumentRetentionApplied, agreementInfo.isDocumentRetentionApplied) &&
        Objects.equals(this.lastEventDate, agreementInfo.lastEventDate) &&
        Objects.equals(this.locale, agreementInfo.locale) &&
        Objects.equals(this.mergeFieldInfo, agreementInfo.mergeFieldInfo) &&
        Objects.equals(this.message, agreementInfo.message) &&
        Objects.equals(this.name, agreementInfo.name) &&
        Objects.equals(this.notaryInfo, agreementInfo.notaryInfo) &&
        Objects.equals(this.parentId, agreementInfo.parentId) &&
        Objects.equals(this.participantSetsInfo, agreementInfo.participantSetsInfo) &&
        Objects.equals(this.postSignOption, agreementInfo.postSignOption) &&
        Objects.equals(this.reminderFrequency, agreementInfo.reminderFrequency) &&
        Objects.equals(this.securityOption, agreementInfo.securityOption) &&
        Objects.equals(this.sendType, agreementInfo.sendType) &&
        Objects.equals(this.senderEmail, agreementInfo.senderEmail) &&
        Objects.equals(this.senderSigns, agreementInfo.senderSigns) &&
        Objects.equals(this.signatureType, agreementInfo.signatureType) &&
        Objects.equals(this.state, agreementInfo.state) &&
        Objects.equals(this.status, agreementInfo.status) &&
        Objects.equals(this.type, agreementInfo.type) &&
        Objects.equals(this.vaultingInfo, agreementInfo.vaultingInfo) &&
        Objects.equals(this.workflowId, agreementInfo.workflowId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreementSettingsInfo, ccs, createdDate, deviceInfo, documentRetentionAppliedDate, documentVisibilityEnabled, emailOption, expirationTime, externalId, fileInfos, firstReminderDelay, formFieldGenerators, formFieldLayerTemplates, groupId, hasFormFieldData, hasSignerIdentityReport, id, isDocumentRetentionApplied, lastEventDate, locale, mergeFieldInfo, message, name, notaryInfo, parentId, participantSetsInfo, postSignOption, reminderFrequency, securityOption, sendType, senderEmail, senderSigns, signatureType, state, status, type, vaultingInfo, workflowId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementInfo {\n");
    
    sb.append("    agreementSettingsInfo: ").append(toIndentedString(agreementSettingsInfo)).append("\n");
    sb.append("    ccs: ").append(toIndentedString(ccs)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    deviceInfo: ").append(toIndentedString(deviceInfo)).append("\n");
    sb.append("    documentRetentionAppliedDate: ").append(toIndentedString(documentRetentionAppliedDate)).append("\n");
    sb.append("    documentVisibilityEnabled: ").append(toIndentedString(documentVisibilityEnabled)).append("\n");
    sb.append("    emailOption: ").append(toIndentedString(emailOption)).append("\n");
    sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    fileInfos: ").append(toIndentedString(fileInfos)).append("\n");
    sb.append("    firstReminderDelay: ").append(toIndentedString(firstReminderDelay)).append("\n");
    sb.append("    formFieldGenerators: ").append(toIndentedString(formFieldGenerators)).append("\n");
    sb.append("    formFieldLayerTemplates: ").append(toIndentedString(formFieldLayerTemplates)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    hasFormFieldData: ").append(toIndentedString(hasFormFieldData)).append("\n");
    sb.append("    hasSignerIdentityReport: ").append(toIndentedString(hasSignerIdentityReport)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isDocumentRetentionApplied: ").append(toIndentedString(isDocumentRetentionApplied)).append("\n");
    sb.append("    lastEventDate: ").append(toIndentedString(lastEventDate)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    mergeFieldInfo: ").append(toIndentedString(mergeFieldInfo)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    notaryInfo: ").append(toIndentedString(notaryInfo)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    participantSetsInfo: ").append(toIndentedString(participantSetsInfo)).append("\n");
    sb.append("    postSignOption: ").append(toIndentedString(postSignOption)).append("\n");
    sb.append("    reminderFrequency: ").append(toIndentedString(reminderFrequency)).append("\n");
    sb.append("    securityOption: ").append(toIndentedString(securityOption)).append("\n");
    sb.append("    sendType: ").append(toIndentedString(sendType)).append("\n");
    sb.append("    senderEmail: ").append(toIndentedString(senderEmail)).append("\n");
    sb.append("    senderSigns: ").append(toIndentedString(senderSigns)).append("\n");
    sb.append("    signatureType: ").append(toIndentedString(signatureType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    vaultingInfo: ").append(toIndentedString(vaultingInfo)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
