/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsSecurityOption;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementsMemberInfos
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsMemberInfos {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("securityOption")
  private AgreementsSecurityOption securityOption = null;

  public AgreementsMemberInfos email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the participant. In case of creating new Agreements(POST/PUT), this is a required field.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AgreementsMemberInfos id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the participant. This will be ignored as part of POST or PUT calls. The Id might be null in draft state
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgreementsMemberInfos name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Recipient&#x27;s full name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AgreementsMemberInfos securityOption(AgreementsSecurityOption securityOption) {
    this.securityOption = securityOption;
    return this;
  }

   /**
   * Get securityOption
   * @return securityOption
  **/
  public AgreementsSecurityOption getSecurityOption() {
    return securityOption;
  }

  public void setSecurityOption(AgreementsSecurityOption securityOption) {
    this.securityOption = securityOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsMemberInfos agreementsMemberInfos = (AgreementsMemberInfos) o;
    return Objects.equals(this.email, agreementsMemberInfos.email) &&
        Objects.equals(this.id, agreementsMemberInfos.id) &&
        Objects.equals(this.name, agreementsMemberInfos.name) &&
        Objects.equals(this.securityOption, agreementsMemberInfos.securityOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, id, name, securityOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsMemberInfos {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    securityOption: ").append(toIndentedString(securityOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
