/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementsPostSignOption
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsPostSignOption {
  @JsonProperty("redirectDelay")
  private Integer redirectDelay = null;

  @JsonProperty("redirectUrl")
  private String redirectUrl = null;

  public AgreementsPostSignOption redirectDelay(Integer redirectDelay) {
    this.redirectDelay = redirectDelay;
    return this;
  }

   /**
   * The delay (in seconds) before the user is taken to the success page. If this value is greater than 0, the user will first see the standard Acrobat Sign success message, and then after a delay will be redirected to your success page
   * @return redirectDelay
  **/
  public Integer getRedirectDelay() {
    return redirectDelay;
  }

  public void setRedirectDelay(Integer redirectDelay) {
    this.redirectDelay = redirectDelay;
  }

  public AgreementsPostSignOption redirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * A publicly accessible url to which the user will be sent after successfully completing the signing process
   * @return redirectUrl
  **/
  public String getRedirectUrl() {
    return redirectUrl;
  }

  public void setRedirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsPostSignOption agreementsPostSignOption = (AgreementsPostSignOption) o;
    return Objects.equals(this.redirectDelay, agreementsPostSignOption.redirectDelay) &&
        Objects.equals(this.redirectUrl, agreementsPostSignOption.redirectUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redirectDelay, redirectUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsPostSignOption {\n");
    
    sb.append("    redirectDelay: ").append(toIndentedString(redirectDelay)).append("\n");
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
