/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementDocumentsSupportingDocuments
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementDocumentsSupportingDocuments {
  @JsonProperty("displayLabel")
  private String displayLabel = null;

  @JsonProperty("fieldName")
  private String fieldName = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("mimeType")
  private String mimeType = null;

  @JsonProperty("numPages")
  private Integer numPages = null;

  @JsonProperty("participantId")
  private String participantId = null;

  public AgreementDocumentsSupportingDocuments displayLabel(String displayLabel) {
    this.displayLabel = displayLabel;
    return this;
  }

   /**
   * Display name of the document
   * @return displayLabel
  **/
  public String getDisplayLabel() {
    return displayLabel;
  }

  public void setDisplayLabel(String displayLabel) {
    this.displayLabel = displayLabel;
  }

  public AgreementDocumentsSupportingDocuments fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * The name of the supporting document field
   * @return fieldName
  **/
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public AgreementDocumentsSupportingDocuments id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id representing the document
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgreementDocumentsSupportingDocuments mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * Mime-type of the document
   * @return mimeType
  **/
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public AgreementDocumentsSupportingDocuments numPages(Integer numPages) {
    this.numPages = numPages;
    return this;
  }

   /**
   * Number of pages in the document
   * @return numPages
  **/
  public Integer getNumPages() {
    return numPages;
  }

  public void setNumPages(Integer numPages) {
    this.numPages = numPages;
  }

  public AgreementDocumentsSupportingDocuments participantId(String participantId) {
    this.participantId = participantId;
    return this;
  }

   /**
   * The unique identifier of the participant that uploaded the supporting document
   * @return participantId
  **/
  public String getParticipantId() {
    return participantId;
  }

  public void setParticipantId(String participantId) {
    this.participantId = participantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementDocumentsSupportingDocuments agreementDocumentsSupportingDocuments = (AgreementDocumentsSupportingDocuments) o;
    return Objects.equals(this.displayLabel, agreementDocumentsSupportingDocuments.displayLabel) &&
        Objects.equals(this.fieldName, agreementDocumentsSupportingDocuments.fieldName) &&
        Objects.equals(this.id, agreementDocumentsSupportingDocuments.id) &&
        Objects.equals(this.mimeType, agreementDocumentsSupportingDocuments.mimeType) &&
        Objects.equals(this.numPages, agreementDocumentsSupportingDocuments.numPages) &&
        Objects.equals(this.participantId, agreementDocumentsSupportingDocuments.participantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayLabel, fieldName, id, mimeType, numPages, participantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementDocumentsSupportingDocuments {\n");
    
    sb.append("    displayLabel: ").append(toIndentedString(displayLabel)).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    numPages: ").append(toIndentedString(numPages)).append("\n");
    sb.append("    participantId: ").append(toIndentedString(participantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
