/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementsagreementIdviewsCommonViewConfigurationPostSendOption
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsagreementIdviewsCommonViewConfigurationPostSendOption {
  @JsonProperty("redirectUrl")
  private String redirectUrl = null;

  public AgreementsagreementIdviewsCommonViewConfigurationPostSendOption redirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * URL to redirect to after completion of the SEND flow. Specified URL must be part of the allow list for application redirects, configured by a CSR Admin
   * @return redirectUrl
  **/
  public String getRedirectUrl() {
    return redirectUrl;
  }

  public void setRedirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsagreementIdviewsCommonViewConfigurationPostSendOption agreementsagreementIdviewsCommonViewConfigurationPostSendOption = (AgreementsagreementIdviewsCommonViewConfigurationPostSendOption) o;
    return Objects.equals(this.redirectUrl, agreementsagreementIdviewsCommonViewConfigurationPostSendOption.redirectUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redirectUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsagreementIdviewsCommonViewConfigurationPostSendOption {\n");
    
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
