/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Additional information for agreements that require notarization
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsNotaryInfo {
  @JsonProperty("appointment")
  private String appointment = null;

  @JsonProperty("notaryEmail")
  private String notaryEmail = null;

  /**
   * PROVIDER_NOTARY: Notary is provided by the notary provider BYON_NOTARY: In house Notary is provided by the customer
   */
  public enum NotaryTypeEnum {
    PROVIDER_NOTARY("PROVIDER_NOTARY"),
    BYON_NOTARY("BYON_NOTARY");

    private String value;

    NotaryTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static NotaryTypeEnum fromValue(String input) {
      for (NotaryTypeEnum b : NotaryTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("notaryType")
  private NotaryTypeEnum notaryType = null;

  @JsonProperty("note")
  private String note = null;

  /**
   * BY_SENDER: When the notarization provider provides the notary and the notary fee will be paid by the sender BY_SIGNER: When the notarization provider provides the notary and the notary fee will be paid by the signer
   */
  public enum PaymentEnum {
    SENDER("BY_SENDER"),
    SIGNER("BY_SIGNER");

    private String value;

    PaymentEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PaymentEnum fromValue(String input) {
      for (PaymentEnum b : PaymentEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("payment")
  private PaymentEnum payment = null;

  public AgreementsNotaryInfo appointment(String appointment) {
    this.appointment = appointment;
    return this;
  }

   /**
   * A proposed appointment time specified using the yyyy-MM-dd&#x27;T&#x27;HH:mm:ssZ format.
   * @return appointment
  **/
  public String getAppointment() {
    return appointment;
  }

  public void setAppointment(String appointment) {
    this.appointment = appointment;
  }

  public AgreementsNotaryInfo notaryEmail(String notaryEmail) {
    this.notaryEmail = notaryEmail;
    return this;
  }

   /**
   * Email address of provided notary when the notaryType is BYON_NOTARY
   * @return notaryEmail
  **/
  public String getNotaryEmail() {
    return notaryEmail;
  }

  public void setNotaryEmail(String notaryEmail) {
    this.notaryEmail = notaryEmail;
  }

  public AgreementsNotaryInfo notaryType(NotaryTypeEnum notaryType) {
    this.notaryType = notaryType;
    return this;
  }

   /**
   * PROVIDER_NOTARY: Notary is provided by the notary provider BYON_NOTARY: In house Notary is provided by the customer
   * @return notaryType
  **/
  public NotaryTypeEnum getNotaryType() {
    return notaryType;
  }

  public void setNotaryType(NotaryTypeEnum notaryType) {
    this.notaryType = notaryType;
  }

  public AgreementsNotaryInfo note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Notes for the notary session.
   * @return note
  **/
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public AgreementsNotaryInfo payment(PaymentEnum payment) {
    this.payment = payment;
    return this;
  }

   /**
   * BY_SENDER: When the notarization provider provides the notary and the notary fee will be paid by the sender BY_SIGNER: When the notarization provider provides the notary and the notary fee will be paid by the signer
   * @return payment
  **/
  public PaymentEnum getPayment() {
    return payment;
  }

  public void setPayment(PaymentEnum payment) {
    this.payment = payment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsNotaryInfo agreementsNotaryInfo = (AgreementsNotaryInfo) o;
    return Objects.equals(this.appointment, agreementsNotaryInfo.appointment) &&
        Objects.equals(this.notaryEmail, agreementsNotaryInfo.notaryEmail) &&
        Objects.equals(this.notaryType, agreementsNotaryInfo.notaryType) &&
        Objects.equals(this.note, agreementsNotaryInfo.note) &&
        Objects.equals(this.payment, agreementsNotaryInfo.payment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appointment, notaryEmail, notaryType, note, payment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsNotaryInfo {\n");
    
    sb.append("    appointment: ").append(toIndentedString(appointment)).append("\n");
    sb.append("    notaryEmail: ").append(toIndentedString(notaryEmail)).append("\n");
    sb.append("    notaryType: ").append(toIndentedString(notaryType)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
