/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsSecurityOption;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
/**
 * AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos {
  @JsonProperty("company")
  private String company = null;

  @JsonProperty("createdDate")
  private LocalDate createdDate = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("hidden")
  private Boolean hidden = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("privateMessage")
  private String privateMessage = null;

  @JsonProperty("securityOption")
  private AgreementsSecurityOption securityOption = null;

  @JsonProperty("self")
  private Boolean self = null;

  /**
   * The status of the participant. This cannot be changed as part of the PUT call. New participants will be ignored if added with a REPLACED status.
   */
  public enum StatusEnum {
    REPLACED("REPLACED"),
    ACTIVE("ACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("userId")
  private String userId = null;

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos company(String company) {
    this.company = company;
    return this;
  }

   /**
   * The company of the participant, if available. This cannot be changed as part of the PUT call.
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos createdDate(LocalDate createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The date when the participant was added. This will be returned as part of GET call but is ignored if passed as part of PUT call.
   * @return createdDate
  **/
  public LocalDate getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(LocalDate createdDate) {
    this.createdDate = createdDate;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the participant. In case of modifying a participant set (PUT) this is a required field. In case of GET, this is the required field and will always be returned unless it is a fax workflow (legacy agreements) that were created using fax as input
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * True if the agreement is hidden for the user that is calling the API. Only returned if self is true. Ignored (not required) if modifying a participant (PUT).
   * @return hidden
  **/
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the participant. This will be returned as part of Get call but is not mandatory to be passed as part of PUT call for agreements/{id}/members/participantSets/{id}.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the participant, if available. This cannot be changed as part of the PUT call.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos privateMessage(String privateMessage) {
    this.privateMessage = privateMessage;
    return this;
  }

   /**
   * The private message of the participant, if available. This cannot be changed as part of the PUT call.
   * @return privateMessage
  **/
  public String getPrivateMessage() {
    return privateMessage;
  }

  public void setPrivateMessage(String privateMessage) {
    this.privateMessage = privateMessage;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos securityOption(AgreementsSecurityOption securityOption) {
    this.securityOption = securityOption;
    return this;
  }

   /**
   * Get securityOption
   * @return securityOption
  **/
  public AgreementsSecurityOption getSecurityOption() {
    return securityOption;
  }

  public void setSecurityOption(AgreementsSecurityOption securityOption) {
    this.securityOption = securityOption;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * True if this participant is the same user that is calling the API. Returned as part of Get. Ignored (not required) if modifying a participant set (PUT).
   * @return self
  **/
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the participant. This cannot be changed as part of the PUT call. New participants will be ignored if added with a REPLACED status.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The user ID of the participant. This will be returned as part of GET call but is ignored if passed as part of PUT call.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos = (AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos) o;
    return Objects.equals(this.company, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.company) &&
        Objects.equals(this.createdDate, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.createdDate) &&
        Objects.equals(this.email, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.email) &&
        Objects.equals(this.hidden, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.hidden) &&
        Objects.equals(this.id, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.id) &&
        Objects.equals(this.name, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.name) &&
        Objects.equals(this.privateMessage, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.privateMessage) &&
        Objects.equals(this.securityOption, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.securityOption) &&
        Objects.equals(this.self, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.self) &&
        Objects.equals(this.status, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.status) &&
        Objects.equals(this.userId, agreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, createdDate, email, hidden, id, name, privateMessage, securityOption, self, status, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    privateMessage: ").append(toIndentedString(privateMessage)).append("\n");
    sb.append("    securityOption: ").append(toIndentedString(securityOption)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
