/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementEventDeviceLocation;
import api.rest.v6.client.AgreementEventDigitalSignatureInfo;
import api.rest.v6.client.AgreementEventElectronicSealInfo;
import api.rest.v6.client.AgreementEventReminderParticipants;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
/**
 * AgreementEventListEvents
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementEventListEvents {
  @JsonProperty("actingUserEmail")
  private String actingUserEmail = null;

  @JsonProperty("actingUserIpAddress")
  private String actingUserIpAddress = null;

  @JsonProperty("actingUserName")
  private String actingUserName = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("date")
  private LocalDate date = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("device")
  private String device = null;

  @JsonProperty("deviceLocation")
  private AgreementEventDeviceLocation deviceLocation = null;

  @JsonProperty("devicePhoneNumber")
  private String devicePhoneNumber = null;

  @JsonProperty("digitalSignatureInfo")
  private AgreementEventDigitalSignatureInfo digitalSignatureInfo = null;

  @JsonProperty("electronicSealInfo")
  private AgreementEventElectronicSealInfo electronicSealInfo = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("initiatingUserEmail")
  private String initiatingUserEmail = null;

  @JsonProperty("initiatingUserName")
  private String initiatingUserName = null;

  @JsonProperty("participantEmail")
  private String participantEmail = null;

  @JsonProperty("participantId")
  private String participantId = null;

  /**
   * Role assumed by all participants in the participant set the participant belongs to (signer, approver etc.).
   */
  public enum ParticipantRoleEnum {
    SIGNER("SIGNER"),
    DELEGATE_TO_SIGNER("DELEGATE_TO_SIGNER"),
    APPROVER("APPROVER"),
    DELEGATE_TO_APPROVER("DELEGATE_TO_APPROVER"),
    ACCEPTOR("ACCEPTOR"),
    DELEGATE_TO_ACCEPTOR("DELEGATE_TO_ACCEPTOR"),
    FORM_FILLER("FORM_FILLER"),
    DELEGATE_TO_FORM_FILLER("DELEGATE_TO_FORM_FILLER"),
    CERTIFIED_RECIPIENT("CERTIFIED_RECIPIENT"),
    DELEGATE_TO_CERTIFIED_RECIPIENT("DELEGATE_TO_CERTIFIED_RECIPIENT"),
    SHARE("SHARE"),
    RESOURCE_SHARE("RESOURCE_SHARE"),
    SENDER("SENDER"),
    NOTARY_SIGNER("NOTARY_SIGNER"),
    ELECTRONIC_SEALER("ELECTRONIC_SEALER");

    private String value;

    ParticipantRoleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ParticipantRoleEnum fromValue(String input) {
      for (ParticipantRoleEnum b : ParticipantRoleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("participantRole")
  private ParticipantRoleEnum participantRole = null;

  @JsonProperty("reminderParticipants")
  private List<AgreementEventReminderParticipants> reminderParticipants = null;

  @JsonProperty("replacedParticipantEmail")
  private String replacedParticipantEmail = null;

  @JsonProperty("replacedParticipantName")
  private String replacedParticipantName = null;

  @JsonProperty("signerNewName")
  private String signerNewName = null;

  @JsonProperty("signerOldName")
  private String signerOldName = null;

  @JsonProperty("signingReason")
  private String signingReason = null;

  @JsonProperty("synchronizationId")
  private String synchronizationId = null;

  /**
   * Type of agreement event
   */
  public enum TypeEnum {
    ACCESS_CODE_GENERATED("ACCESS_CODE_GENERATED"),
    ACCESS_CODE_CONSUMED("ACCESS_CODE_CONSUMED"),
    AUTO_CANCELLED_CONVERSION_PROBLEM("AUTO_CANCELLED_CONVERSION_PROBLEM"),
    ACTION_AUTO_DELEGATED("ACTION_AUTO_DELEGATED"),
    ACTION_COMPLETED("ACTION_COMPLETED"),
    ACTION_COMPLETED_HOSTED("ACTION_COMPLETED_HOSTED"),
    ACTION_COMPLETED_OFFLINE("ACTION_COMPLETED_OFFLINE"),
    ACTION_COMPLETED_OFFLINE_HOSTED("ACTION_COMPLETED_OFFLINE_HOSTED"),
    ACTION_COMPLETED_WIDGET_VERIFIED("ACTION_COMPLETED_WIDGET_VERIFIED"),
    ACTION_COMPLETED_WIDGET_VERIFIED_API_TOKEN("ACTION_COMPLETED_WIDGET_VERIFIED_API_TOKEN"),
    ACTION_COMPLETED_WIDGET_VERIFICATION_WAIVED("ACTION_COMPLETED_WIDGET_VERIFICATION_WAIVED"),
    ACTION_DELEGATED("ACTION_DELEGATED"),
    ACTION_REPLACED_SIGNER("ACTION_REPLACED_SIGNER"),
    ACTION_REQUESTED("ACTION_REQUESTED"),
    CREATED("CREATED"),
    CREATED_FROM_WIDGET("CREATED_FROM_WIDGET"),
    CREATED_OFFLINE("CREATED_OFFLINE"),
    CREATED_VIA_UPLOAD("CREATED_VIA_UPLOAD"),
    CREATED_VIA_ACROBAT("CREATED_VIA_ACROBAT"),
    CREATED_VIA_READER("CREATED_VIA_READER"),
    ACTIVATED("ACTIVATED"),
    DIGITAL_SIGN_UIDAI_SIGNER_CONSENT("DIGITAL_SIGN_UIDAI_SIGNER_CONSENT"),
    DIGSIGNED("DIGSIGNED"),
    DEACTIVATED("DEACTIVATED"),
    DOCUMENTS_DELETED("DOCUMENTS_DELETED"),
    DOWNLOADED("DOWNLOADED"),
    DELETED("DELETED"),
    EMAIL_BOUNCED("EMAIL_BOUNCED"),
    EMAIL_VIEWED("EMAIL_VIEWED"),
    EXPIRED("EXPIRED"),
    EXPIRED_AUTOMATICALLY("EXPIRED_AUTOMATICALLY"),
    FAXED_BY_SENDER("FAXED_BY_SENDER"),
    FAXIN_RECEIVED("FAXIN_RECEIVED"),
    KBA_AUTHENTICATED("KBA_AUTHENTICATED"),
    MODIFIED("MODIFIED"),
    OFFLINE_SYNC("OFFLINE_SYNC"),
    OTHER("OTHER"),
    PAID("PAID"),
    PRESIGNED("PRESIGNED"),
    RECALLED("RECALLED"),
    RECALLED_MAX_SIGNING_KBA_ATTEMPTS("RECALLED_MAX_SIGNING_KBA_ATTEMPTS"),
    RECALLED_MAX_SIGNING_PASSWORD_ATTEMPTS("RECALLED_MAX_SIGNING_PASSWORD_ATTEMPTS"),
    RECALLED_MAX_SIGNING_PHONE_ATTEMPTS("RECALLED_MAX_SIGNING_PHONE_ATTEMPTS"),
    REJECTED("REJECTED"),
    RESTARTED("RESTARTED"),
    RECOVERED("RECOVERED"),
    SENDER_CREATED_NEW_REVISION("SENDER_CREATED_NEW_REVISION"),
    SHARED("SHARED"),
    SIGNED("SIGNED"),
    SIGNING_URL_REQUESTED("SIGNING_URL_REQUESTED"),
    UPLOADED_BY_SENDER("UPLOADED_BY_SENDER"),
    USER_ACK_AGREEMENT_MODIFIED("USER_ACK_AGREEMENT_MODIFIED"),
    READY_TO_VAULT("READY_TO_VAULT"),
    VAULTED("VAULTED"),
    WEB_IDENTITY_AUTHENTICATED("WEB_IDENTITY_AUTHENTICATED"),
    WEB_IDENTITY_SPECIFIED("WEB_IDENTITY_SPECIFIED"),
    WRITTEN_DOWNLOAD("WRITTEN_DOWNLOAD"),
    WRITTEN_SIGNED("WRITTEN_SIGNED"),
    READY_TO_NOTARIZE("READY_TO_NOTARIZE"),
    NOTARIZED("NOTARIZED"),
    NOTARY_TRANSACTION("NOTARY_TRANSACTION"),
    SIGNER_NAME_CHANGED_BY_SIGNER("SIGNER_NAME_CHANGED_BY_SIGNER"),
    ELECTRONICALLY_SEALED("ELECTRONICALLY_SEALED"),
    URL_REAUTHENTICATION_REQUESTED("URL_REAUTHENTICATION_REQUESTED"),
    REMINDER_SENT("REMINDER_SENT"),
    DOCUMENTS_VIEWED("DOCUMENTS_VIEWED"),
    DOCUMENTS_VIEWED_HOSTED("DOCUMENTS_VIEWED_HOSTED"),
    DOCUMENTS_VIEWED_PASSWORD_PROTECTED("DOCUMENTS_VIEWED_PASSWORD_PROTECTED"),
    REMINDER_INITIATED("REMINDER_INITIATED");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("vaultEventId")
  private String vaultEventId = null;

  @JsonProperty("vaultProviderName")
  private String vaultProviderName = null;

  @JsonProperty("versionId")
  private String versionId = null;

  public AgreementEventListEvents actingUserEmail(String actingUserEmail) {
    this.actingUserEmail = actingUserEmail;
    return this;
  }

   /**
   * Email address of the user that created the event
   * @return actingUserEmail
  **/
  public String getActingUserEmail() {
    return actingUserEmail;
  }

  public void setActingUserEmail(String actingUserEmail) {
    this.actingUserEmail = actingUserEmail;
  }

  public AgreementEventListEvents actingUserIpAddress(String actingUserIpAddress) {
    this.actingUserIpAddress = actingUserIpAddress;
    return this;
  }

   /**
   * The IP address of the user that created the event
   * @return actingUserIpAddress
  **/
  public String getActingUserIpAddress() {
    return actingUserIpAddress;
  }

  public void setActingUserIpAddress(String actingUserIpAddress) {
    this.actingUserIpAddress = actingUserIpAddress;
  }

  public AgreementEventListEvents actingUserName(String actingUserName) {
    this.actingUserName = actingUserName;
    return this;
  }

   /**
   * The name of the acting user
   * @return actingUserName
  **/
  public String getActingUserName() {
    return actingUserName;
  }

  public void setActingUserName(String actingUserName) {
    this.actingUserName = actingUserName;
  }

  public AgreementEventListEvents comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * The event comment. For RECALLED or REJECTED, the reason given by the user that initiates the event. For DELEGATE or SHARE, the message from the acting user to the participant
   * @return comment
  **/
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public AgreementEventListEvents date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * The date of the audit event. Format would be yyyy-MM-dd&#x27;T&#x27;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
   * @return date
  **/
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public AgreementEventListEvents description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the audit event
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AgreementEventListEvents device(String device) {
    this.device = device;
    return this;
  }

   /**
   * The device used for the event.
   * @return device
  **/
  public String getDevice() {
    return device;
  }

  public void setDevice(String device) {
    this.device = device;
  }

  public AgreementEventListEvents deviceLocation(AgreementEventDeviceLocation deviceLocation) {
    this.deviceLocation = deviceLocation;
    return this;
  }

   /**
   * Get deviceLocation
   * @return deviceLocation
  **/
  public AgreementEventDeviceLocation getDeviceLocation() {
    return deviceLocation;
  }

  public void setDeviceLocation(AgreementEventDeviceLocation deviceLocation) {
    this.deviceLocation = deviceLocation;
  }

  public AgreementEventListEvents devicePhoneNumber(String devicePhoneNumber) {
    this.devicePhoneNumber = devicePhoneNumber;
    return this;
  }

   /**
   * Phone number from the device used when the participation is completed on a mobile phone
   * @return devicePhoneNumber
  **/
  public String getDevicePhoneNumber() {
    return devicePhoneNumber;
  }

  public void setDevicePhoneNumber(String devicePhoneNumber) {
    this.devicePhoneNumber = devicePhoneNumber;
  }

  public AgreementEventListEvents digitalSignatureInfo(AgreementEventDigitalSignatureInfo digitalSignatureInfo) {
    this.digitalSignatureInfo = digitalSignatureInfo;
    return this;
  }

   /**
   * Get digitalSignatureInfo
   * @return digitalSignatureInfo
  **/
  public AgreementEventDigitalSignatureInfo getDigitalSignatureInfo() {
    return digitalSignatureInfo;
  }

  public void setDigitalSignatureInfo(AgreementEventDigitalSignatureInfo digitalSignatureInfo) {
    this.digitalSignatureInfo = digitalSignatureInfo;
  }

  public AgreementEventListEvents electronicSealInfo(AgreementEventElectronicSealInfo electronicSealInfo) {
    this.electronicSealInfo = electronicSealInfo;
    return this;
  }

   /**
   * Get electronicSealInfo
   * @return electronicSealInfo
  **/
  public AgreementEventElectronicSealInfo getElectronicSealInfo() {
    return electronicSealInfo;
  }

  public void setElectronicSealInfo(AgreementEventElectronicSealInfo electronicSealInfo) {
    this.electronicSealInfo = electronicSealInfo;
  }

  public AgreementEventListEvents id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier for the event.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgreementEventListEvents initiatingUserEmail(String initiatingUserEmail) {
    this.initiatingUserEmail = initiatingUserEmail;
    return this;
  }

   /**
   * Email address of the user that initiated the event on behalf of the acting user when the account is shared. Will be empty if there is no account sharing in effect
   * @return initiatingUserEmail
  **/
  public String getInitiatingUserEmail() {
    return initiatingUserEmail;
  }

  public void setInitiatingUserEmail(String initiatingUserEmail) {
    this.initiatingUserEmail = initiatingUserEmail;
  }

  public AgreementEventListEvents initiatingUserName(String initiatingUserName) {
    this.initiatingUserName = initiatingUserName;
    return this;
  }

   /**
   * Full name of the user that initiated the event on behalf of the acting user when the account is shared. Will be empty if there is no account sharing in effect
   * @return initiatingUserName
  **/
  public String getInitiatingUserName() {
    return initiatingUserName;
  }

  public void setInitiatingUserName(String initiatingUserName) {
    this.initiatingUserName = initiatingUserName;
  }

  public AgreementEventListEvents participantEmail(String participantEmail) {
    this.participantEmail = participantEmail;
    return this;
  }

   /**
   * Email address of the user that is the participant for the event. This may be different than the acting user for certain event types. For example, for a DELEGATION event, this is the user who was delegated to
   * @return participantEmail
  **/
  public String getParticipantEmail() {
    return participantEmail;
  }

  public void setParticipantEmail(String participantEmail) {
    this.participantEmail = participantEmail;
  }

  public AgreementEventListEvents participantId(String participantId) {
    this.participantId = participantId;
    return this;
  }

   /**
   * The unique identifier of the participant for the event. This may be different than the acting user for certain event types. For example, for a DELEGATION event, this is the user who was delegated to
   * @return participantId
  **/
  public String getParticipantId() {
    return participantId;
  }

  public void setParticipantId(String participantId) {
    this.participantId = participantId;
  }

  public AgreementEventListEvents participantRole(ParticipantRoleEnum participantRole) {
    this.participantRole = participantRole;
    return this;
  }

   /**
   * Role assumed by all participants in the participant set the participant belongs to (signer, approver etc.).
   * @return participantRole
  **/
  public ParticipantRoleEnum getParticipantRole() {
    return participantRole;
  }

  public void setParticipantRole(ParticipantRoleEnum participantRole) {
    this.participantRole = participantRole;
  }

  public AgreementEventListEvents reminderParticipants(List<AgreementEventReminderParticipants> reminderParticipants) {
    this.reminderParticipants = reminderParticipants;
    return this;
  }

  public AgreementEventListEvents addReminderParticipantsItem(AgreementEventReminderParticipants reminderParticipantsItem) {
    if (this.reminderParticipants == null) {
      this.reminderParticipants = new ArrayList<>();
    }
    this.reminderParticipants.add(reminderParticipantsItem);
    return this;
  }

   /**
   * A list of one or more participants who received the reminders
   * @return reminderParticipants
  **/
  public List<AgreementEventReminderParticipants> getReminderParticipants() {
    return reminderParticipants;
  }

  public void setReminderParticipants(List<AgreementEventReminderParticipants> reminderParticipants) {
    this.reminderParticipants = reminderParticipants;
  }

  public AgreementEventListEvents replacedParticipantEmail(String replacedParticipantEmail) {
    this.replacedParticipantEmail = replacedParticipantEmail;
    return this;
  }

   /**
   * Email of the user that was replaced by the participant for the event. This may be different than the acting user for certain event types. For example, for a DELEGATION event, this is the user who was delegated to
   * @return replacedParticipantEmail
  **/
  public String getReplacedParticipantEmail() {
    return replacedParticipantEmail;
  }

  public void setReplacedParticipantEmail(String replacedParticipantEmail) {
    this.replacedParticipantEmail = replacedParticipantEmail;
  }

  public AgreementEventListEvents replacedParticipantName(String replacedParticipantName) {
    this.replacedParticipantName = replacedParticipantName;
    return this;
  }

   /**
   * Full name of the user that was replaced by the participant for the event. This may be different than the acting user for certain event types. For example, for a DELEGATION event, this is the user who was delegated to
   * @return replacedParticipantName
  **/
  public String getReplacedParticipantName() {
    return replacedParticipantName;
  }

  public void setReplacedParticipantName(String replacedParticipantName) {
    this.replacedParticipantName = replacedParticipantName;
  }

  public AgreementEventListEvents signerNewName(String signerNewName) {
    this.signerNewName = signerNewName;
    return this;
  }

   /**
   * Signer changed name at signing : new name used to sign.
   * @return signerNewName
  **/
  public String getSignerNewName() {
    return signerNewName;
  }

  public void setSignerNewName(String signerNewName) {
    this.signerNewName = signerNewName;
  }

  public AgreementEventListEvents signerOldName(String signerOldName) {
    this.signerOldName = signerOldName;
    return this;
  }

   /**
   * Signer changed name at signing : name used previous to signing.
   * @return signerOldName
  **/
  public String getSignerOldName() {
    return signerOldName;
  }

  public void setSignerOldName(String signerOldName) {
    this.signerOldName = signerOldName;
  }

  public AgreementEventListEvents signingReason(String signingReason) {
    this.signingReason = signingReason;
    return this;
  }

   /**
   * Signing reason captured during ESIGN or DIGSIGN
   * @return signingReason
  **/
  public String getSigningReason() {
    return signingReason;
  }

  public void setSigningReason(String signingReason) {
    this.signingReason = signingReason;
  }

  public AgreementEventListEvents synchronizationId(String synchronizationId) {
    this.synchronizationId = synchronizationId;
    return this;
  }

   /**
   * A unique identifier linking offline events to synchronization events (specified for offline signing events and synchronization events, else null)
   * @return synchronizationId
  **/
  public String getSynchronizationId() {
    return synchronizationId;
  }

  public void setSynchronizationId(String synchronizationId) {
    this.synchronizationId = synchronizationId;
  }

  public AgreementEventListEvents type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Type of agreement event
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AgreementEventListEvents vaultEventId(String vaultEventId) {
    this.vaultEventId = vaultEventId;
    return this;
  }

   /**
   * The identifier assigned by the vault provider for the vault event (if vaulted, otherwise null)
   * @return vaultEventId
  **/
  public String getVaultEventId() {
    return vaultEventId;
  }

  public void setVaultEventId(String vaultEventId) {
    this.vaultEventId = vaultEventId;
  }

  public AgreementEventListEvents vaultProviderName(String vaultProviderName) {
    this.vaultProviderName = vaultProviderName;
    return this;
  }

   /**
   * Name of the vault provider for the vault event (if vaulted, otherwise null)
   * @return vaultProviderName
  **/
  public String getVaultProviderName() {
    return vaultProviderName;
  }

  public void setVaultProviderName(String vaultProviderName) {
    this.vaultProviderName = vaultProviderName;
  }

  public AgreementEventListEvents versionId(String versionId) {
    this.versionId = versionId;
    return this;
  }

   /**
   * An ID which uniquely identifies the version of the document associated with this audit event
   * @return versionId
  **/
  public String getVersionId() {
    return versionId;
  }

  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementEventListEvents agreementEventListEvents = (AgreementEventListEvents) o;
    return Objects.equals(this.actingUserEmail, agreementEventListEvents.actingUserEmail) &&
        Objects.equals(this.actingUserIpAddress, agreementEventListEvents.actingUserIpAddress) &&
        Objects.equals(this.actingUserName, agreementEventListEvents.actingUserName) &&
        Objects.equals(this.comment, agreementEventListEvents.comment) &&
        Objects.equals(this.date, agreementEventListEvents.date) &&
        Objects.equals(this.description, agreementEventListEvents.description) &&
        Objects.equals(this.device, agreementEventListEvents.device) &&
        Objects.equals(this.deviceLocation, agreementEventListEvents.deviceLocation) &&
        Objects.equals(this.devicePhoneNumber, agreementEventListEvents.devicePhoneNumber) &&
        Objects.equals(this.digitalSignatureInfo, agreementEventListEvents.digitalSignatureInfo) &&
        Objects.equals(this.electronicSealInfo, agreementEventListEvents.electronicSealInfo) &&
        Objects.equals(this.id, agreementEventListEvents.id) &&
        Objects.equals(this.initiatingUserEmail, agreementEventListEvents.initiatingUserEmail) &&
        Objects.equals(this.initiatingUserName, agreementEventListEvents.initiatingUserName) &&
        Objects.equals(this.participantEmail, agreementEventListEvents.participantEmail) &&
        Objects.equals(this.participantId, agreementEventListEvents.participantId) &&
        Objects.equals(this.participantRole, agreementEventListEvents.participantRole) &&
        Objects.equals(this.reminderParticipants, agreementEventListEvents.reminderParticipants) &&
        Objects.equals(this.replacedParticipantEmail, agreementEventListEvents.replacedParticipantEmail) &&
        Objects.equals(this.replacedParticipantName, agreementEventListEvents.replacedParticipantName) &&
        Objects.equals(this.signerNewName, agreementEventListEvents.signerNewName) &&
        Objects.equals(this.signerOldName, agreementEventListEvents.signerOldName) &&
        Objects.equals(this.signingReason, agreementEventListEvents.signingReason) &&
        Objects.equals(this.synchronizationId, agreementEventListEvents.synchronizationId) &&
        Objects.equals(this.type, agreementEventListEvents.type) &&
        Objects.equals(this.vaultEventId, agreementEventListEvents.vaultEventId) &&
        Objects.equals(this.vaultProviderName, agreementEventListEvents.vaultProviderName) &&
        Objects.equals(this.versionId, agreementEventListEvents.versionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actingUserEmail, actingUserIpAddress, actingUserName, comment, date, description, device, deviceLocation, devicePhoneNumber, digitalSignatureInfo, electronicSealInfo, id, initiatingUserEmail, initiatingUserName, participantEmail, participantId, participantRole, reminderParticipants, replacedParticipantEmail, replacedParticipantName, signerNewName, signerOldName, signingReason, synchronizationId, type, vaultEventId, vaultProviderName, versionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementEventListEvents {\n");
    
    sb.append("    actingUserEmail: ").append(toIndentedString(actingUserEmail)).append("\n");
    sb.append("    actingUserIpAddress: ").append(toIndentedString(actingUserIpAddress)).append("\n");
    sb.append("    actingUserName: ").append(toIndentedString(actingUserName)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    deviceLocation: ").append(toIndentedString(deviceLocation)).append("\n");
    sb.append("    devicePhoneNumber: ").append(toIndentedString(devicePhoneNumber)).append("\n");
    sb.append("    digitalSignatureInfo: ").append(toIndentedString(digitalSignatureInfo)).append("\n");
    sb.append("    electronicSealInfo: ").append(toIndentedString(electronicSealInfo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    initiatingUserEmail: ").append(toIndentedString(initiatingUserEmail)).append("\n");
    sb.append("    initiatingUserName: ").append(toIndentedString(initiatingUserName)).append("\n");
    sb.append("    participantEmail: ").append(toIndentedString(participantEmail)).append("\n");
    sb.append("    participantId: ").append(toIndentedString(participantId)).append("\n");
    sb.append("    participantRole: ").append(toIndentedString(participantRole)).append("\n");
    sb.append("    reminderParticipants: ").append(toIndentedString(reminderParticipants)).append("\n");
    sb.append("    replacedParticipantEmail: ").append(toIndentedString(replacedParticipantEmail)).append("\n");
    sb.append("    replacedParticipantName: ").append(toIndentedString(replacedParticipantName)).append("\n");
    sb.append("    signerNewName: ").append(toIndentedString(signerNewName)).append("\n");
    sb.append("    signerOldName: ").append(toIndentedString(signerOldName)).append("\n");
    sb.append("    signingReason: ").append(toIndentedString(signingReason)).append("\n");
    sb.append("    synchronizationId: ").append(toIndentedString(synchronizationId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    vaultEventId: ").append(toIndentedString(vaultEventId)).append("\n");
    sb.append("    vaultProviderName: ").append(toIndentedString(vaultProviderName)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
