/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsAnchorTextInfo;
import api.rest.v6.client.AgreementsFormFieldDescription;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Form Field Generator providing information for generating form fields relative to text in the content of the agreement documents
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsFormFieldGenerators {
  @JsonProperty("anchorTextInfo")
  private AgreementsAnchorTextInfo anchorTextInfo = null;

  @JsonProperty("formFieldDescription")
  private AgreementsFormFieldDescription formFieldDescription = null;

  @JsonProperty("formFieldNamePrefix")
  private String formFieldNamePrefix = null;

  /**
   * The type of form field generator, default ANCHOR_TEXT
   */
  public enum GeneratorTypeEnum {
    ANCHOR_TEXT("ANCHOR_TEXT");

    private String value;

    GeneratorTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static GeneratorTypeEnum fromValue(String input) {
      for (GeneratorTypeEnum b : GeneratorTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("generatorType")
  private GeneratorTypeEnum generatorType = null;

  @JsonProperty("linked")
  private Boolean linked = null;

  @JsonProperty("participantSetName")
  private String participantSetName = null;

  public AgreementsFormFieldGenerators anchorTextInfo(AgreementsAnchorTextInfo anchorTextInfo) {
    this.anchorTextInfo = anchorTextInfo;
    return this;
  }

   /**
   * Get anchorTextInfo
   * @return anchorTextInfo
  **/
  public AgreementsAnchorTextInfo getAnchorTextInfo() {
    return anchorTextInfo;
  }

  public void setAnchorTextInfo(AgreementsAnchorTextInfo anchorTextInfo) {
    this.anchorTextInfo = anchorTextInfo;
  }

  public AgreementsFormFieldGenerators formFieldDescription(AgreementsFormFieldDescription formFieldDescription) {
    this.formFieldDescription = formFieldDescription;
    return this;
  }

   /**
   * Get formFieldDescription
   * @return formFieldDescription
  **/
  public AgreementsFormFieldDescription getFormFieldDescription() {
    return formFieldDescription;
  }

  public void setFormFieldDescription(AgreementsFormFieldDescription formFieldDescription) {
    this.formFieldDescription = formFieldDescription;
  }

  public AgreementsFormFieldGenerators formFieldNamePrefix(String formFieldNamePrefix) {
    this.formFieldNamePrefix = formFieldNamePrefix;
    return this;
  }

   /**
   * The prefix name of each generated form field
   * @return formFieldNamePrefix
  **/
  public String getFormFieldNamePrefix() {
    return formFieldNamePrefix;
  }

  public void setFormFieldNamePrefix(String formFieldNamePrefix) {
    this.formFieldNamePrefix = formFieldNamePrefix;
  }

  public AgreementsFormFieldGenerators generatorType(GeneratorTypeEnum generatorType) {
    this.generatorType = generatorType;
    return this;
  }

   /**
   * The type of form field generator, default ANCHOR_TEXT
   * @return generatorType
  **/
  public GeneratorTypeEnum getGeneratorType() {
    return generatorType;
  }

  public void setGeneratorType(GeneratorTypeEnum generatorType) {
    this.generatorType = generatorType;
  }

  public AgreementsFormFieldGenerators linked(Boolean linked) {
    this.linked = linked;
    return this;
  }

   /**
   * By default duplicate generated form fields will be linked as references unless linked is false in which case unique form fields will be created
   * @return linked
  **/
  public Boolean isLinked() {
    return linked;
  }

  public void setLinked(Boolean linked) {
    this.linked = linked;
  }

  public AgreementsFormFieldGenerators participantSetName(String participantSetName) {
    this.participantSetName = participantSetName;
    return this;
  }

   /**
   * The name of the participant set to assign the generated form field with
   * @return participantSetName
  **/
  public String getParticipantSetName() {
    return participantSetName;
  }

  public void setParticipantSetName(String participantSetName) {
    this.participantSetName = participantSetName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsFormFieldGenerators agreementsFormFieldGenerators = (AgreementsFormFieldGenerators) o;
    return Objects.equals(this.anchorTextInfo, agreementsFormFieldGenerators.anchorTextInfo) &&
        Objects.equals(this.formFieldDescription, agreementsFormFieldGenerators.formFieldDescription) &&
        Objects.equals(this.formFieldNamePrefix, agreementsFormFieldGenerators.formFieldNamePrefix) &&
        Objects.equals(this.generatorType, agreementsFormFieldGenerators.generatorType) &&
        Objects.equals(this.linked, agreementsFormFieldGenerators.linked) &&
        Objects.equals(this.participantSetName, agreementsFormFieldGenerators.participantSetName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anchorTextInfo, formFieldDescription, formFieldNamePrefix, generatorType, linked, participantSetName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsFormFieldGenerators {\n");
    
    sb.append("    anchorTextInfo: ").append(toIndentedString(anchorTextInfo)).append("\n");
    sb.append("    formFieldDescription: ").append(toIndentedString(formFieldDescription)).append("\n");
    sb.append("    formFieldNamePrefix: ").append(toIndentedString(formFieldNamePrefix)).append("\n");
    sb.append("    generatorType: ").append(toIndentedString(generatorType)).append("\n");
    sb.append("    linked: ").append(toIndentedString(linked)).append("\n");
    sb.append("    participantSetName: ").append(toIndentedString(participantSetName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
