/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsagreementIdviewsCommonViewConfigurationPostSendOption;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementsagreementIdviewsCommonViewConfiguration
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsagreementIdviewsCommonViewConfiguration {
  @JsonProperty("autoLoginUser")
  private Boolean autoLoginUser = null;

  @JsonProperty("frameParent")
  private String frameParent = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("noChrome")
  private Boolean noChrome = null;

  @JsonProperty("postSendOption")
  private AgreementsagreementIdviewsCommonViewConfigurationPostSendOption postSendOption = null;

  public AgreementsagreementIdviewsCommonViewConfiguration autoLoginUser(Boolean autoLoginUser) {
    this.autoLoginUser = autoLoginUser;
    return this;
  }

   /**
   * Auto LogIn Flag. If true, the URL returned will automatically log the user in. If false, the URL returned will require the credentials. By default its value is false
   * @return autoLoginUser
  **/
  public Boolean isAutoLoginUser() {
    return autoLoginUser;
  }

  public void setAutoLoginUser(Boolean autoLoginUser) {
    this.autoLoginUser = autoLoginUser;
  }

  public AgreementsagreementIdviewsCommonViewConfiguration frameParent(String frameParent) {
    this.frameParent = frameParent;
    return this;
  }

   /**
   * An optional field to provide the comma-separated list of parent domain urls where the returned URLs may be iframed. If provided with non-empty and valid list of parent domain urls, it will be used to allow framing for the same. By default the value is null and the Acrobat Sign pages will not be viewable in an iframe.
   * @return frameParent
  **/
  public String getFrameParent() {
    return frameParent;
  }

  public void setFrameParent(String frameParent) {
    this.frameParent = frameParent;
  }

  public AgreementsagreementIdviewsCommonViewConfiguration locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Message template locale
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public AgreementsagreementIdviewsCommonViewConfiguration noChrome(Boolean noChrome) {
    this.noChrome = noChrome;
    return this;
  }

   /**
   * No Chrome Flag. If true, the embedded page is shown without a navigation header or footer. If false, the standard page header and footer will be present. By default its value is false
   * @return noChrome
  **/
  public Boolean isNoChrome() {
    return noChrome;
  }

  public void setNoChrome(Boolean noChrome) {
    this.noChrome = noChrome;
  }

  public AgreementsagreementIdviewsCommonViewConfiguration postSendOption(AgreementsagreementIdviewsCommonViewConfigurationPostSendOption postSendOption) {
    this.postSendOption = postSendOption;
    return this;
  }

   /**
   * Get postSendOption
   * @return postSendOption
  **/
  public AgreementsagreementIdviewsCommonViewConfigurationPostSendOption getPostSendOption() {
    return postSendOption;
  }

  public void setPostSendOption(AgreementsagreementIdviewsCommonViewConfigurationPostSendOption postSendOption) {
    this.postSendOption = postSendOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsagreementIdviewsCommonViewConfiguration agreementsagreementIdviewsCommonViewConfiguration = (AgreementsagreementIdviewsCommonViewConfiguration) o;
    return Objects.equals(this.autoLoginUser, agreementsagreementIdviewsCommonViewConfiguration.autoLoginUser) &&
        Objects.equals(this.frameParent, agreementsagreementIdviewsCommonViewConfiguration.frameParent) &&
        Objects.equals(this.locale, agreementsagreementIdviewsCommonViewConfiguration.locale) &&
        Objects.equals(this.noChrome, agreementsagreementIdviewsCommonViewConfiguration.noChrome) &&
        Objects.equals(this.postSendOption, agreementsagreementIdviewsCommonViewConfiguration.postSendOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoLoginUser, frameParent, locale, noChrome, postSendOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsagreementIdviewsCommonViewConfiguration {\n");
    
    sb.append("    autoLoginUser: ").append(toIndentedString(autoLoginUser)).append("\n");
    sb.append("    frameParent: ").append(toIndentedString(frameParent)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    noChrome: ").append(toIndentedString(noChrome)).append("\n");
    sb.append("    postSendOption: ").append(toIndentedString(postSendOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
