/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementsSecurityOptionPhoneInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsSecurityOptionPhoneInfo {
  @JsonProperty("countryCode")
  private String countryCode = null;

  @JsonProperty("countryIsoCode")
  private String countryIsoCode = null;

  @JsonProperty("phone")
  private String phone = null;

  public AgreementsSecurityOptionPhoneInfo countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The numeric country calling code (ISD code) required for the participant to view and sign the document if authentication type is PHONE
   * @return countryCode
  **/
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public AgreementsSecurityOptionPhoneInfo countryIsoCode(String countryIsoCode) {
    this.countryIsoCode = countryIsoCode;
    return this;
  }

   /**
   * The country ISO Alpha-2 code required for the participant to view and sign the document if authentication method is PHONE
   * @return countryIsoCode
  **/
  public String getCountryIsoCode() {
    return countryIsoCode;
  }

  public void setCountryIsoCode(String countryIsoCode) {
    this.countryIsoCode = countryIsoCode;
  }

  public AgreementsSecurityOptionPhoneInfo phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * The phone number required for the participant to view and sign the document if authentication method is PHONE. When replacing a participant that has PHONE authentication specified, you must supply a phone number for the new participant.
   * @return phone
  **/
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsSecurityOptionPhoneInfo agreementsSecurityOptionPhoneInfo = (AgreementsSecurityOptionPhoneInfo) o;
    return Objects.equals(this.countryCode, agreementsSecurityOptionPhoneInfo.countryCode) &&
        Objects.equals(this.countryIsoCode, agreementsSecurityOptionPhoneInfo.countryIsoCode) &&
        Objects.equals(this.phone, agreementsSecurityOptionPhoneInfo.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, countryIsoCode, phone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsSecurityOptionPhoneInfo {\n");
    
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    countryIsoCode: ").append(toIndentedString(countryIsoCode)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
