/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsagreementIdviewsComposeViewConfigurationFileUploadOptions;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AgreementsagreementIdviewsComposeViewConfiguration
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsagreementIdviewsComposeViewConfiguration {
  @JsonProperty("fileUploadOptions")
  private AgreementsagreementIdviewsComposeViewConfigurationFileUploadOptions fileUploadOptions = null;

  @JsonProperty("isPreviewSelected")
  private Boolean isPreviewSelected = null;

  public AgreementsagreementIdviewsComposeViewConfiguration fileUploadOptions(AgreementsagreementIdviewsComposeViewConfigurationFileUploadOptions fileUploadOptions) {
    this.fileUploadOptions = fileUploadOptions;
    return this;
  }

   /**
   * Get fileUploadOptions
   * @return fileUploadOptions
  **/
  public AgreementsagreementIdviewsComposeViewConfigurationFileUploadOptions getFileUploadOptions() {
    return fileUploadOptions;
  }

  public void setFileUploadOptions(AgreementsagreementIdviewsComposeViewConfigurationFileUploadOptions fileUploadOptions) {
    this.fileUploadOptions = fileUploadOptions;
  }

  public AgreementsagreementIdviewsComposeViewConfiguration isPreviewSelected(Boolean isPreviewSelected) {
    this.isPreviewSelected = isPreviewSelected;
    return this;
  }

   /**
   * Should the compose page be provided with authoring mode selected?
   * @return isPreviewSelected
  **/
  public Boolean isIsPreviewSelected() {
    return isPreviewSelected;
  }

  public void setIsPreviewSelected(Boolean isPreviewSelected) {
    this.isPreviewSelected = isPreviewSelected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsagreementIdviewsComposeViewConfiguration agreementsagreementIdviewsComposeViewConfiguration = (AgreementsagreementIdviewsComposeViewConfiguration) o;
    return Objects.equals(this.fileUploadOptions, agreementsagreementIdviewsComposeViewConfiguration.fileUploadOptions) &&
        Objects.equals(this.isPreviewSelected, agreementsagreementIdviewsComposeViewConfiguration.isPreviewSelected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileUploadOptions, isPreviewSelected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsagreementIdviewsComposeViewConfiguration {\n");
    
    sb.append("    fileUploadOptions: ").append(toIndentedString(fileUploadOptions)).append("\n");
    sb.append("    isPreviewSelected: ").append(toIndentedString(isPreviewSelected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
