/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementDocumentImageUrlsInfoImageURLs;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AgreementDocumentImageUrlsInfoDocumentImageUrlsList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementDocumentImageUrlsInfoDocumentImageUrlsList {
  /**
   * ImageSize corresponding to the imageUrl returned 
   */
  public enum ImageSizeEnum {
    FIXED_WIDTH_50PX("FIXED_WIDTH_50px"),
    FIXED_WIDTH_250PX("FIXED_WIDTH_250px"),
    FIXED_WIDTH_675PX("FIXED_WIDTH_675px"),
    ZOOM_50_PERCENT("ZOOM_50_PERCENT"),
    ZOOM_75_PERCENT("ZOOM_75_PERCENT"),
    ZOOM_100_PERCENT("ZOOM_100_PERCENT"),
    ZOOM_125_PERCENT("ZOOM_125_PERCENT"),
    ZOOM_150_PERCENT("ZOOM_150_PERCENT"),
    ZOOM_200_PERCENT("ZOOM_200_PERCENT");

    private String value;

    ImageSizeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ImageSizeEnum fromValue(String input) {
      for (ImageSizeEnum b : ImageSizeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("imageSize")
  private ImageSizeEnum imageSize = null;

  @JsonProperty("imageURLs")
  private List<AgreementDocumentImageUrlsInfoImageURLs> imageURLs = new ArrayList<>();

  @JsonProperty("imagesAvailable")
  private Boolean imagesAvailable = null;

  public AgreementDocumentImageUrlsInfoDocumentImageUrlsList imageSize(ImageSizeEnum imageSize) {
    this.imageSize = imageSize;
    return this;
  }

   /**
   * ImageSize corresponding to the imageUrl returned 
   * @return imageSize
  **/
  public ImageSizeEnum getImageSize() {
    return imageSize;
  }

  public void setImageSize(ImageSizeEnum imageSize) {
    this.imageSize = imageSize;
  }

  public AgreementDocumentImageUrlsInfoDocumentImageUrlsList imageURLs(List<AgreementDocumentImageUrlsInfoImageURLs> imageURLs) {
    this.imageURLs = imageURLs;
    return this;
  }

  public AgreementDocumentImageUrlsInfoDocumentImageUrlsList addImageURLsItem(AgreementDocumentImageUrlsInfoImageURLs imageURLsItem) {
    this.imageURLs.add(imageURLsItem);
    return this;
  }

   /**
   * A list of image url (one per page).
   * @return imageURLs
  **/
  public List<AgreementDocumentImageUrlsInfoImageURLs> getImageURLs() {
    return imageURLs;
  }

  public void setImageURLs(List<AgreementDocumentImageUrlsInfoImageURLs> imageURLs) {
    this.imageURLs = imageURLs;
  }

  public AgreementDocumentImageUrlsInfoDocumentImageUrlsList imagesAvailable(Boolean imagesAvailable) {
    this.imagesAvailable = imagesAvailable;
    return this;
  }

   /**
   * true if images for the associated image size is available, else false.
   * @return imagesAvailable
  **/
  public Boolean isImagesAvailable() {
    return imagesAvailable;
  }

  public void setImagesAvailable(Boolean imagesAvailable) {
    this.imagesAvailable = imagesAvailable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementDocumentImageUrlsInfoDocumentImageUrlsList agreementDocumentImageUrlsInfoDocumentImageUrlsList = (AgreementDocumentImageUrlsInfoDocumentImageUrlsList) o;
    return Objects.equals(this.imageSize, agreementDocumentImageUrlsInfoDocumentImageUrlsList.imageSize) &&
        Objects.equals(this.imageURLs, agreementDocumentImageUrlsInfoDocumentImageUrlsList.imageURLs) &&
        Objects.equals(this.imagesAvailable, agreementDocumentImageUrlsInfoDocumentImageUrlsList.imagesAvailable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageSize, imageURLs, imagesAvailable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementDocumentImageUrlsInfoDocumentImageUrlsList {\n");
    
    sb.append("    imageSize: ").append(toIndentedString(imageSize)).append("\n");
    sb.append("    imageURLs: ").append(toIndentedString(imageURLs)).append("\n");
    sb.append("    imagesAvailable: ").append(toIndentedString(imagesAvailable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
