/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Location information for placing generated form fields relative to the location of text content found within the agreement documents
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class AgreementsAnchorTextInfoAnchoredFormFieldLocation {
  @JsonProperty("height")
  private Double height = null;

  @JsonProperty("offsetX")
  private Double offsetX = null;

  @JsonProperty("offsetY")
  private Double offsetY = null;

  @JsonProperty("width")
  private Double width = null;

  public AgreementsAnchorTextInfoAnchoredFormFieldLocation height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * The generated form field height in default user space units
   * @return height
  **/
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public AgreementsAnchorTextInfoAnchoredFormFieldLocation offsetX(Double offsetX) {
    this.offsetX = offsetX;
    return this;
  }

   /**
   * The x offset from the anchor text to the form field in default user space units
   * @return offsetX
  **/
  public Double getOffsetX() {
    return offsetX;
  }

  public void setOffsetX(Double offsetX) {
    this.offsetX = offsetX;
  }

  public AgreementsAnchorTextInfoAnchoredFormFieldLocation offsetY(Double offsetY) {
    this.offsetY = offsetY;
    return this;
  }

   /**
   * The y offset from the anchor text to the form field in default user space units
   * @return offsetY
  **/
  public Double getOffsetY() {
    return offsetY;
  }

  public void setOffsetY(Double offsetY) {
    this.offsetY = offsetY;
  }

  public AgreementsAnchorTextInfoAnchoredFormFieldLocation width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * The generated form field width in default user space units
   * @return width
  **/
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementsAnchorTextInfoAnchoredFormFieldLocation agreementsAnchorTextInfoAnchoredFormFieldLocation = (AgreementsAnchorTextInfoAnchoredFormFieldLocation) o;
    return Objects.equals(this.height, agreementsAnchorTextInfoAnchoredFormFieldLocation.height) &&
        Objects.equals(this.offsetX, agreementsAnchorTextInfoAnchoredFormFieldLocation.offsetX) &&
        Objects.equals(this.offsetY, agreementsAnchorTextInfoAnchoredFormFieldLocation.offsetY) &&
        Objects.equals(this.width, agreementsAnchorTextInfoAnchoredFormFieldLocation.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, offsetX, offsetY, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementsAnchorTextInfoAnchoredFormFieldLocation {\n");
    
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    offsetX: ").append(toIndentedString(offsetX)).append("\n");
    sb.append("    offsetY: ").append(toIndentedString(offsetY)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
