/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.CombinedDocumentPagesInfoDocumentPagesInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * CombinedDocumentPagesInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class CombinedDocumentPagesInfo {
  @JsonProperty("documentPagesInfo")
  private List<CombinedDocumentPagesInfoDocumentPagesInfo> documentPagesInfo = new ArrayList<>();

  public CombinedDocumentPagesInfo documentPagesInfo(List<CombinedDocumentPagesInfoDocumentPagesInfo> documentPagesInfo) {
    this.documentPagesInfo = documentPagesInfo;
    return this;
  }

  public CombinedDocumentPagesInfo addDocumentPagesInfoItem(CombinedDocumentPagesInfoDocumentPagesInfo documentPagesInfoItem) {
    this.documentPagesInfo.add(documentPagesInfoItem);
    return this;
  }

   /**
   * List of basic information of all pages of the combined document of an Agreement.
   * @return documentPagesInfo
  **/
  public List<CombinedDocumentPagesInfoDocumentPagesInfo> getDocumentPagesInfo() {
    return documentPagesInfo;
  }

  public void setDocumentPagesInfo(List<CombinedDocumentPagesInfoDocumentPagesInfo> documentPagesInfo) {
    this.documentPagesInfo = documentPagesInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CombinedDocumentPagesInfo combinedDocumentPagesInfo = (CombinedDocumentPagesInfo) o;
    return Objects.equals(this.documentPagesInfo, combinedDocumentPagesInfo.documentPagesInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentPagesInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CombinedDocumentPagesInfo {\n");
    
    sb.append("    documentPagesInfo: ").append(toIndentedString(documentPagesInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
