/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsagreementIdmembersparticipantSetsparticipantSetIddelegatedParticipantSetsSecurityOption;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DelegatedParticipantInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class DelegatedParticipantInfo {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("fullName")
  private String fullName = null;

  @JsonProperty("securityOption")
  private AgreementsagreementIdmembersparticipantSetsparticipantSetIddelegatedParticipantSetsSecurityOption securityOption = null;

  public DelegatedParticipantInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the participant. In case of modifying a participant set (PUT) this is a required field. In case of GET, this is the required field and will always be returned unless it is a fax workflow (legacy agreements) that were created using fax as input
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public DelegatedParticipantInfo fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * The full name of the delegatee, if available.
   * @return fullName
  **/
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public DelegatedParticipantInfo securityOption(AgreementsagreementIdmembersparticipantSetsparticipantSetIddelegatedParticipantSetsSecurityOption securityOption) {
    this.securityOption = securityOption;
    return this;
  }

   /**
   * Get securityOption
   * @return securityOption
  **/
  public AgreementsagreementIdmembersparticipantSetsparticipantSetIddelegatedParticipantSetsSecurityOption getSecurityOption() {
    return securityOption;
  }

  public void setSecurityOption(AgreementsagreementIdmembersparticipantSetsparticipantSetIddelegatedParticipantSetsSecurityOption securityOption) {
    this.securityOption = securityOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DelegatedParticipantInfo delegatedParticipantInfo = (DelegatedParticipantInfo) o;
    return Objects.equals(this.email, delegatedParticipantInfo.email) &&
        Objects.equals(this.fullName, delegatedParticipantInfo.fullName) &&
        Objects.equals(this.securityOption, delegatedParticipantInfo.securityOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, fullName, securityOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DelegatedParticipantInfo {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    securityOption: ").append(toIndentedString(securityOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
