/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.DisplayParticipantSetInfoDisplayUserSetMemberInfos;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DisplayParticipantSetInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class DisplayParticipantSetInfo {
  @JsonProperty("displayUserSetMemberInfos")
  private List<DisplayParticipantSetInfoDisplayUserSetMemberInfos> displayUserSetMemberInfos = new ArrayList<>();

  @JsonProperty("displayUserSetName")
  private String displayUserSetName = null;

  public DisplayParticipantSetInfo displayUserSetMemberInfos(List<DisplayParticipantSetInfoDisplayUserSetMemberInfos> displayUserSetMemberInfos) {
    this.displayUserSetMemberInfos = displayUserSetMemberInfos;
    return this;
  }

  public DisplayParticipantSetInfo addDisplayUserSetMemberInfosItem(DisplayParticipantSetInfoDisplayUserSetMemberInfos displayUserSetMemberInfosItem) {
    this.displayUserSetMemberInfos.add(displayUserSetMemberInfosItem);
    return this;
  }

   /**
   * Displays the info about user set
   * @return displayUserSetMemberInfos
  **/
  public List<DisplayParticipantSetInfoDisplayUserSetMemberInfos> getDisplayUserSetMemberInfos() {
    return displayUserSetMemberInfos;
  }

  public void setDisplayUserSetMemberInfos(List<DisplayParticipantSetInfoDisplayUserSetMemberInfos> displayUserSetMemberInfos) {
    this.displayUserSetMemberInfos = displayUserSetMemberInfos;
  }

  public DisplayParticipantSetInfo displayUserSetName(String displayUserSetName) {
    this.displayUserSetName = displayUserSetName;
    return this;
  }

   /**
   * The name of the display user set. Returned only, if the API caller is the sender of agreement. 
   * @return displayUserSetName
  **/
  public String getDisplayUserSetName() {
    return displayUserSetName;
  }

  public void setDisplayUserSetName(String displayUserSetName) {
    this.displayUserSetName = displayUserSetName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisplayParticipantSetInfo displayParticipantSetInfo = (DisplayParticipantSetInfo) o;
    return Objects.equals(this.displayUserSetMemberInfos, displayParticipantSetInfo.displayUserSetMemberInfos) &&
        Objects.equals(this.displayUserSetName, displayParticipantSetInfo.displayUserSetName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayUserSetMemberInfos, displayUserSetName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisplayParticipantSetInfo {\n");
    
    sb.append("    displayUserSetMemberInfos: ").append(toIndentedString(displayUserSetMemberInfos)).append("\n");
    sb.append("    displayUserSetName: ").append(toIndentedString(displayUserSetName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
