/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DisplayParticipantSetInfoDisplayUserSetMemberInfos
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class DisplayParticipantSetInfoDisplayUserSetMemberInfos {
  @JsonProperty("company")
  private String company = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("fullName")
  private String fullName = null;

  public DisplayParticipantSetInfoDisplayUserSetMemberInfos company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Displays the name of the company of the user, if available
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public DisplayParticipantSetInfoDisplayUserSetMemberInfos email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Displays the email of the user
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public DisplayParticipantSetInfoDisplayUserSetMemberInfos fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Displays the full name of the user, if available. 
   * @return fullName
  **/
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisplayParticipantSetInfoDisplayUserSetMemberInfos displayParticipantSetInfoDisplayUserSetMemberInfos = (DisplayParticipantSetInfoDisplayUserSetMemberInfos) o;
    return Objects.equals(this.company, displayParticipantSetInfoDisplayUserSetMemberInfos.company) &&
        Objects.equals(this.email, displayParticipantSetInfoDisplayUserSetMemberInfos.email) &&
        Objects.equals(this.fullName, displayParticipantSetInfoDisplayUserSetMemberInfos.fullName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, email, fullName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisplayParticipantSetInfoDisplayUserSetMemberInfos {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
