/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DocumentPageInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class DocumentPageInfo {
  @JsonProperty("height")
  private Double height = null;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("rotation")
  private Double rotation = null;

  @JsonProperty("width")
  private Double width = null;

  public DocumentPageInfo height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * Height of the page
   * @return height
  **/
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public DocumentPageInfo index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the page in combined document starting from 1
   * @return index
  **/
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public DocumentPageInfo rotation(Double rotation) {
    this.rotation = rotation;
    return this;
  }

   /**
   * Rotation angle of the page in clockwise direction in degree
   * @return rotation
  **/
  public Double getRotation() {
    return rotation;
  }

  public void setRotation(Double rotation) {
    this.rotation = rotation;
  }

  public DocumentPageInfo width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * Width of the page
   * @return width
  **/
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentPageInfo documentPageInfo = (DocumentPageInfo) o;
    return Objects.equals(this.height, documentPageInfo.height) &&
        Objects.equals(this.index, documentPageInfo.index) &&
        Objects.equals(this.rotation, documentPageInfo.rotation) &&
        Objects.equals(this.width, documentPageInfo.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, index, rotation, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentPageInfo {\n");
    
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    rotation: ").append(toIndentedString(rotation)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
