/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementDocumentImageUrlsInfoDocumentImageUrlsList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DocumentImageUrlsInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class DocumentImageUrlsInfo {
  @JsonProperty("documentId")
  private String documentId = null;

  @JsonProperty("documentImageUrlsList")
  private List<AgreementDocumentImageUrlsInfoDocumentImageUrlsList> documentImageUrlsList = new ArrayList<>();

  public DocumentImageUrlsInfo documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Id of the document
   * @return documentId
  **/
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public DocumentImageUrlsInfo documentImageUrlsList(List<AgreementDocumentImageUrlsInfoDocumentImageUrlsList> documentImageUrlsList) {
    this.documentImageUrlsList = documentImageUrlsList;
    return this;
  }

  public DocumentImageUrlsInfo addDocumentImageUrlsListItem(AgreementDocumentImageUrlsInfoDocumentImageUrlsList documentImageUrlsListItem) {
    this.documentImageUrlsList.add(documentImageUrlsListItem);
    return this;
  }

   /**
   * A list of documents image URLs.
   * @return documentImageUrlsList
  **/
  public List<AgreementDocumentImageUrlsInfoDocumentImageUrlsList> getDocumentImageUrlsList() {
    return documentImageUrlsList;
  }

  public void setDocumentImageUrlsList(List<AgreementDocumentImageUrlsInfoDocumentImageUrlsList> documentImageUrlsList) {
    this.documentImageUrlsList = documentImageUrlsList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentImageUrlsInfo documentImageUrlsInfo = (DocumentImageUrlsInfo) o;
    return Objects.equals(this.documentId, documentImageUrlsInfo.documentId) &&
        Objects.equals(this.documentImageUrlsList, documentImageUrlsInfo.documentImageUrlsList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, documentImageUrlsList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentImageUrlsInfo {\n");
    
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    documentImageUrlsList: ").append(toIndentedString(documentImageUrlsList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
