/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsDocument;
import api.rest.v6.client.AgreementsUrlFileInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FileInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class FileInfo {
  @JsonProperty("document")
  private AgreementsDocument document = null;

  @JsonProperty("label")
  private String label = null;

  @JsonProperty("libraryDocumentId")
  private String libraryDocumentId = null;

  @JsonProperty("notarize")
  private Boolean notarize = null;

  @JsonProperty("transientDocumentId")
  private String transientDocumentId = null;

  @JsonProperty("urlFileInfo")
  private AgreementsUrlFileInfo urlFileInfo = null;

  public FileInfo document(AgreementsDocument document) {
    this.document = document;
    return this;
  }

   /**
   * Get document
   * @return document
  **/
  public AgreementsDocument getDocument() {
    return document;
  }

  public void setDocument(AgreementsDocument document) {
    this.document = document;
  }

  public FileInfo label(String label) {
    this.label = label;
    return this;
  }

   /**
   * The unique label value of a file info element. In case of custom workflow this will map a file to corresponding file element in workflow definition. This must be specified in case of custom workflow agreement creation request 
   * @return label
  **/
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public FileInfo libraryDocumentId(String libraryDocumentId) {
    this.libraryDocumentId = libraryDocumentId;
    return this;
  }

   /**
   * ID for an existing Library document that will be added to the agreement
   * @return libraryDocumentId
  **/
  public String getLibraryDocumentId() {
    return libraryDocumentId;
  }

  public void setLibraryDocumentId(String libraryDocumentId) {
    this.libraryDocumentId = libraryDocumentId;
  }

  public FileInfo notarize(Boolean notarize) {
    this.notarize = notarize;
    return this;
  }

   /**
   * Indicates that this document needs to be notarized
   * @return notarize
  **/
  public Boolean isNotarize() {
    return notarize;
  }

  public void setNotarize(Boolean notarize) {
    this.notarize = notarize;
  }

  public FileInfo transientDocumentId(String transientDocumentId) {
    this.transientDocumentId = transientDocumentId;
    return this;
  }

   /**
   * ID for a transient document that will be added to the agreement
   * @return transientDocumentId
  **/
  public String getTransientDocumentId() {
    return transientDocumentId;
  }

  public void setTransientDocumentId(String transientDocumentId) {
    this.transientDocumentId = transientDocumentId;
  }

  public FileInfo urlFileInfo(AgreementsUrlFileInfo urlFileInfo) {
    this.urlFileInfo = urlFileInfo;
    return this;
  }

   /**
   * Get urlFileInfo
   * @return urlFileInfo
  **/
  public AgreementsUrlFileInfo getUrlFileInfo() {
    return urlFileInfo;
  }

  public void setUrlFileInfo(AgreementsUrlFileInfo urlFileInfo) {
    this.urlFileInfo = urlFileInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileInfo fileInfo = (FileInfo) o;
    return Objects.equals(this.document, fileInfo.document) &&
        Objects.equals(this.label, fileInfo.label) &&
        Objects.equals(this.libraryDocumentId, fileInfo.libraryDocumentId) &&
        Objects.equals(this.notarize, fileInfo.notarize) &&
        Objects.equals(this.transientDocumentId, fileInfo.transientDocumentId) &&
        Objects.equals(this.urlFileInfo, fileInfo.urlFileInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(document, label, libraryDocumentId, notarize, transientDocumentId, urlFileInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileInfo {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    libraryDocumentId: ").append(toIndentedString(libraryDocumentId)).append("\n");
    sb.append("    notarize: ").append(toIndentedString(notarize)).append("\n");
    sb.append("    transientDocumentId: ").append(toIndentedString(transientDocumentId)).append("\n");
    sb.append("    urlFileInfo: ").append(toIndentedString(urlFileInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
