/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FileUploadOptions
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class FileUploadOptions {
  @JsonProperty("canEditFiles")
  private Boolean canEditFiles = null;

  @JsonProperty("libraryDocument")
  private Boolean libraryDocument = null;

  @JsonProperty("localFile")
  private Boolean localFile = null;

  @JsonProperty("webConnectors")
  private Boolean webConnectors = null;

  public FileUploadOptions canEditFiles(Boolean canEditFiles) {
    this.canEditFiles = canEditFiles;
    return this;
  }

   /**
   * Whether the file upload section can be edited by adding or removing files. Default value is taken as true. Changing the default value will alter the compose page view configuration for this agreement, but is not an access control mechanism
   * @return canEditFiles
  **/
  public Boolean isCanEditFiles() {
    return canEditFiles;
  }

  public void setCanEditFiles(Boolean canEditFiles) {
    this.canEditFiles = canEditFiles;
  }

  public FileUploadOptions libraryDocument(Boolean libraryDocument) {
    this.libraryDocument = libraryDocument;
    return this;
  }

   /**
   * Whether library documents link should appear or not. Default value is taken as true
   * @return libraryDocument
  **/
  public Boolean isLibraryDocument() {
    return libraryDocument;
  }

  public void setLibraryDocument(Boolean libraryDocument) {
    this.libraryDocument = libraryDocument;
  }

  public FileUploadOptions localFile(Boolean localFile) {
    this.localFile = localFile;
    return this;
  }

   /**
   * Whether local file upload button should appear or not. Default value is taken as true
   * @return localFile
  **/
  public Boolean isLocalFile() {
    return localFile;
  }

  public void setLocalFile(Boolean localFile) {
    this.localFile = localFile;
  }

  public FileUploadOptions webConnectors(Boolean webConnectors) {
    this.webConnectors = webConnectors;
    return this;
  }

   /**
   * Whether link to attach documents from web sources like Dropbox should appear or not. Default value is taken as true
   * @return webConnectors
  **/
  public Boolean isWebConnectors() {
    return webConnectors;
  }

  public void setWebConnectors(Boolean webConnectors) {
    this.webConnectors = webConnectors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileUploadOptions fileUploadOptions = (FileUploadOptions) o;
    return Objects.equals(this.canEditFiles, fileUploadOptions.canEditFiles) &&
        Objects.equals(this.libraryDocument, fileUploadOptions.libraryDocument) &&
        Objects.equals(this.localFile, fileUploadOptions.localFile) &&
        Objects.equals(this.webConnectors, fileUploadOptions.webConnectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canEditFiles, libraryDocument, localFile, webConnectors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileUploadOptions {\n");
    
    sb.append("    canEditFiles: ").append(toIndentedString(canEditFiles)).append("\n");
    sb.append("    libraryDocument: ").append(toIndentedString(libraryDocument)).append("\n");
    sb.append("    localFile: ").append(toIndentedString(localFile)).append("\n");
    sb.append("    webConnectors: ").append(toIndentedString(webConnectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
