/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Location information for form fields
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class FormFieldLocation {
  @JsonProperty("height")
  private Double height = null;

  @JsonProperty("left")
  private Double left = null;

  @JsonProperty("pageNumber")
  private Integer pageNumber = null;

  @JsonProperty("top")
  private Double top = null;

  @JsonProperty("width")
  private Double width = null;

  public FormFieldLocation height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * Height of the form field in default user space units
   * @return height
  **/
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public FormFieldLocation left(Double left) {
    this.left = left;
    return this;
  }

   /**
   * No. of default user space units from left of the page for form field placement
   * @return left
  **/
  public Double getLeft() {
    return left;
  }

  public void setLeft(Double left) {
    this.left = left;
  }

  public FormFieldLocation pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Number of the page where form field has to be placed, starting from 1.
   * @return pageNumber
  **/
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public FormFieldLocation top(Double top) {
    this.top = top;
    return this;
  }

   /**
   * No. of default user space units from bottom of the page for form field placement
   * @return top
  **/
  public Double getTop() {
    return top;
  }

  public void setTop(Double top) {
    this.top = top;
  }

  public FormFieldLocation width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * Width of the form field in default user space units
   * @return width
  **/
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormFieldLocation formFieldLocation = (FormFieldLocation) o;
    return Objects.equals(this.height, formFieldLocation.height) &&
        Objects.equals(this.left, formFieldLocation.left) &&
        Objects.equals(this.pageNumber, formFieldLocation.pageNumber) &&
        Objects.equals(this.top, formFieldLocation.top) &&
        Objects.equals(this.width, formFieldLocation.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, left, pageNumber, top, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormFieldLocation {\n");
    
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
