/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsFormFieldDescriptionConditionalActionPredicates;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Conditional actions to perfom on this form field.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class FormFieldConditionalAction {
  /**
   * Action to show/hide the form field is to be taken on the basis of evaluation of conditions.
   */
  public enum ActionEnum {
    SHOW("SHOW"),
    HIDE("HIDE"),
    DISABLE("DISABLE"),
    ENABLE("ENABLE");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ActionEnum fromValue(String input) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("action")
  private ActionEnum action = null;

  /**
   * It indicates if any one of the conditions or all of them have to be true.
   */
  public enum AnyOrAllEnum {
    ALL("ALL"),
    ANY("ANY");

    private String value;

    AnyOrAllEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AnyOrAllEnum fromValue(String input) {
      for (AnyOrAllEnum b : AnyOrAllEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("anyOrAll")
  private AnyOrAllEnum anyOrAll = null;

  @JsonProperty("predicates")
  private List<AgreementsFormFieldDescriptionConditionalActionPredicates> predicates = null;

  public FormFieldConditionalAction action(ActionEnum action) {
    this.action = action;
    return this;
  }

   /**
   * Action to show/hide the form field is to be taken on the basis of evaluation of conditions.
   * @return action
  **/
  public ActionEnum getAction() {
    return action;
  }

  public void setAction(ActionEnum action) {
    this.action = action;
  }

  public FormFieldConditionalAction anyOrAll(AnyOrAllEnum anyOrAll) {
    this.anyOrAll = anyOrAll;
    return this;
  }

   /**
   * It indicates if any one of the conditions or all of them have to be true.
   * @return anyOrAll
  **/
  public AnyOrAllEnum getAnyOrAll() {
    return anyOrAll;
  }

  public void setAnyOrAll(AnyOrAllEnum anyOrAll) {
    this.anyOrAll = anyOrAll;
  }

  public FormFieldConditionalAction predicates(List<AgreementsFormFieldDescriptionConditionalActionPredicates> predicates) {
    this.predicates = predicates;
    return this;
  }

  public FormFieldConditionalAction addPredicatesItem(AgreementsFormFieldDescriptionConditionalActionPredicates predicatesItem) {
    if (this.predicates == null) {
      this.predicates = new ArrayList<>();
    }
    this.predicates.add(predicatesItem);
    return this;
  }

   /**
   * The predicates to be evaluated in order to determine whether this condition is true
   * @return predicates
  **/
  public List<AgreementsFormFieldDescriptionConditionalActionPredicates> getPredicates() {
    return predicates;
  }

  public void setPredicates(List<AgreementsFormFieldDescriptionConditionalActionPredicates> predicates) {
    this.predicates = predicates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormFieldConditionalAction formFieldConditionalAction = (FormFieldConditionalAction) o;
    return Objects.equals(this.action, formFieldConditionalAction.action) &&
        Objects.equals(this.anyOrAll, formFieldConditionalAction.anyOrAll) &&
        Objects.equals(this.predicates, formFieldConditionalAction.predicates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, anyOrAll, predicates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormFieldConditionalAction {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    anyOrAll: ").append(toIndentedString(anyOrAll)).append("\n");
    sb.append("    predicates: ").append(toIndentedString(predicates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
