/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.SigningUrlResponseSigningUrlSetInfos;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20021
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class InlineResponse20021 {
  @JsonProperty("signingUrlSetInfos")
  private List<SigningUrlResponseSigningUrlSetInfos> signingUrlSetInfos = new ArrayList<>();

  public InlineResponse20021 signingUrlSetInfos(List<SigningUrlResponseSigningUrlSetInfos> signingUrlSetInfos) {
    this.signingUrlSetInfos = signingUrlSetInfos;
    return this;
  }

  public InlineResponse20021 addSigningUrlSetInfosItem(SigningUrlResponseSigningUrlSetInfos signingUrlSetInfosItem) {
    this.signingUrlSetInfos.add(signingUrlSetInfosItem);
    return this;
  }

   /**
   * An array of urls for signer sets involved in this agreement.
   * @return signingUrlSetInfos
  **/
  public List<SigningUrlResponseSigningUrlSetInfos> getSigningUrlSetInfos() {
    return signingUrlSetInfos;
  }

  public void setSigningUrlSetInfos(List<SigningUrlResponseSigningUrlSetInfos> signingUrlSetInfos) {
    this.signingUrlSetInfos = signingUrlSetInfos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20021 inlineResponse20021 = (InlineResponse20021) o;
    return Objects.equals(this.signingUrlSetInfos, inlineResponse20021.signingUrlSetInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signingUrlSetInfos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20021 {\n");
    
    sb.append("    signingUrlSetInfos: ").append(toIndentedString(signingUrlSetInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
