/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsMergeFieldInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Data for updating the default values of existing form fields
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class InlineResponse20010 {
  @JsonProperty("fieldMergeInfos")
  private List<AgreementsMergeFieldInfo> fieldMergeInfos = null;

  public InlineResponse20010 fieldMergeInfos(List<AgreementsMergeFieldInfo> fieldMergeInfos) {
    this.fieldMergeInfos = fieldMergeInfos;
    return this;
  }

  public InlineResponse20010 addFieldMergeInfosItem(AgreementsMergeFieldInfo fieldMergeInfosItem) {
    if (this.fieldMergeInfos == null) {
      this.fieldMergeInfos = new ArrayList<>();
    }
    this.fieldMergeInfos.add(fieldMergeInfosItem);
    return this;
  }

   /**
   * A mapping of field names to default values
   * @return fieldMergeInfos
  **/
  public List<AgreementsMergeFieldInfo> getFieldMergeInfos() {
    return fieldMergeInfos;
  }

  public void setFieldMergeInfos(List<AgreementsMergeFieldInfo> fieldMergeInfos) {
    this.fieldMergeInfos = fieldMergeInfos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010 inlineResponse20010 = (InlineResponse20010) o;
    return Objects.equals(this.fieldMergeInfos, inlineResponse20010.fieldMergeInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldMergeInfos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010 {\n");
    
    sb.append("    fieldMergeInfos: ").append(toIndentedString(fieldMergeInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
