/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementViewsAgreementViewList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20022
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class InlineResponse20022 {
  @JsonProperty("agreementViewList")
  private List<AgreementViewsAgreementViewList> agreementViewList = new ArrayList<>();

  public InlineResponse20022 agreementViewList(List<AgreementViewsAgreementViewList> agreementViewList) {
    this.agreementViewList = agreementViewList;
    return this;
  }

  public InlineResponse20022 addAgreementViewListItem(AgreementViewsAgreementViewList agreementViewListItem) {
    this.agreementViewList.add(agreementViewListItem);
    return this;
  }

   /**
   * List of agreement views
   * @return agreementViewList
  **/
  public List<AgreementViewsAgreementViewList> getAgreementViewList() {
    return agreementViewList;
  }

  public void setAgreementViewList(List<AgreementViewsAgreementViewList> agreementViewList) {
    this.agreementViewList = agreementViewList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20022 inlineResponse20022 = (InlineResponse20022) o;
    return Objects.equals(this.agreementViewList, inlineResponse20022.agreementViewList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreementViewList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20022 {\n");
    
    sb.append("    agreementViewList: ").append(toIndentedString(agreementViewList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
