/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementDocumentsSupportingDocuments;
import api.rest.v6.client.AgreementsDocument;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2005
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class InlineResponse2005 {
  @JsonProperty("documents")
  private List<AgreementsDocument> documents = new ArrayList<>();

  @JsonProperty("supportingDocuments")
  private List<AgreementDocumentsSupportingDocuments> supportingDocuments = null;

  public InlineResponse2005 documents(List<AgreementsDocument> documents) {
    this.documents = documents;
    return this;
  }

  public InlineResponse2005 addDocumentsItem(AgreementsDocument documentsItem) {
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * A list of documents
   * @return documents
  **/
  public List<AgreementsDocument> getDocuments() {
    return documents;
  }

  public void setDocuments(List<AgreementsDocument> documents) {
    this.documents = documents;
  }

  public InlineResponse2005 supportingDocuments(List<AgreementDocumentsSupportingDocuments> supportingDocuments) {
    this.supportingDocuments = supportingDocuments;
    return this;
  }

  public InlineResponse2005 addSupportingDocumentsItem(AgreementDocumentsSupportingDocuments supportingDocumentsItem) {
    if (this.supportingDocuments == null) {
      this.supportingDocuments = new ArrayList<>();
    }
    this.supportingDocuments.add(supportingDocumentsItem);
    return this;
  }

   /**
   * A list of supporting documents
   * @return supportingDocuments
  **/
  public List<AgreementDocumentsSupportingDocuments> getSupportingDocuments() {
    return supportingDocuments;
  }

  public void setSupportingDocuments(List<AgreementDocumentsSupportingDocuments> supportingDocuments) {
    this.supportingDocuments = supportingDocuments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return Objects.equals(this.documents, inlineResponse2005.documents) &&
        Objects.equals(this.supportingDocuments, inlineResponse2005.supportingDocuments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documents, supportingDocuments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    supportingDocuments: ").append(toIndentedString(supportingDocuments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
