/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.RemindersReminderIdBody;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20018
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class InlineResponse20018 {
  @JsonProperty("reminderInfoList")
  private List<RemindersReminderIdBody> reminderInfoList = new ArrayList<>();

  public InlineResponse20018 reminderInfoList(List<RemindersReminderIdBody> reminderInfoList) {
    this.reminderInfoList = reminderInfoList;
    return this;
  }

  public InlineResponse20018 addReminderInfoListItem(RemindersReminderIdBody reminderInfoListItem) {
    this.reminderInfoList.add(reminderInfoListItem);
    return this;
  }

   /**
   * A list of one or more reminders created on the agreement specified by the unique identifier agreementId by the user invoking the API.
   * @return reminderInfoList
  **/
  public List<RemindersReminderIdBody> getReminderInfoList() {
    return reminderInfoList;
  }

  public void setReminderInfoList(List<RemindersReminderIdBody> reminderInfoList) {
    this.reminderInfoList = reminderInfoList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20018 inlineResponse20018 = (InlineResponse20018) o;
    return Objects.equals(this.reminderInfoList, inlineResponse20018.reminderInfoList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reminderInfoList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20018 {\n");
    
    sb.append("    reminderInfoList: ").append(toIndentedString(reminderInfoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
