/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.MyAgreementInfoAccountSharers;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MyAgreementInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class MyAgreementInfo {
  @JsonProperty("accountSharers")
  private List<MyAgreementInfoAccountSharers> accountSharers = new ArrayList<>();

  public MyAgreementInfo accountSharers(List<MyAgreementInfoAccountSharers> accountSharers) {
    this.accountSharers = accountSharers;
    return this;
  }

  public MyAgreementInfo addAccountSharersItem(MyAgreementInfoAccountSharers accountSharersItem) {
    this.accountSharers.add(accountSharersItem);
    return this;
  }

   /**
   * A list of account sharer in relation to the api caller and this resource.
   * @return accountSharers
  **/
  public List<MyAgreementInfoAccountSharers> getAccountSharers() {
    return accountSharers;
  }

  public void setAccountSharers(List<MyAgreementInfoAccountSharers> accountSharers) {
    this.accountSharers = accountSharers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyAgreementInfo myAgreementInfo = (MyAgreementInfo) o;
    return Objects.equals(this.accountSharers, myAgreementInfo.accountSharers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountSharers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyAgreementInfo {\n");
    
    sb.append("    accountSharers: ").append(toIndentedString(accountSharers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
