/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.MembersInfoSharesInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MyShareInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class MyShareInfo {
  @JsonProperty("mySharesInfo")
  private List<MembersInfoSharesInfo> mySharesInfo = new ArrayList<>();

  @JsonProperty("shareParticipantInfo")
  private List<MembersInfoSharesInfo> shareParticipantInfo = new ArrayList<>();

  public MyShareInfo mySharesInfo(List<MembersInfoSharesInfo> mySharesInfo) {
    this.mySharesInfo = mySharesInfo;
    return this;
  }

  public MyShareInfo addMySharesInfoItem(MembersInfoSharesInfo mySharesInfoItem) {
    this.mySharesInfo.add(mySharesInfoItem);
    return this;
  }

   /**
   * Information of the participants with whom the agreement has been shared directly by the originator.
   * @return mySharesInfo
  **/
  public List<MembersInfoSharesInfo> getMySharesInfo() {
    return mySharesInfo;
  }

  public void setMySharesInfo(List<MembersInfoSharesInfo> mySharesInfo) {
    this.mySharesInfo = mySharesInfo;
  }

  public MyShareInfo shareParticipantInfo(List<MembersInfoSharesInfo> shareParticipantInfo) {
    this.shareParticipantInfo = shareParticipantInfo;
    return this;
  }

  public MyShareInfo addShareParticipantInfoItem(MembersInfoSharesInfo shareParticipantInfoItem) {
    this.shareParticipantInfo.add(shareParticipantInfoItem);
    return this;
  }

   /**
   * Information of the participants with whom the agreement has been shared.
   * @return shareParticipantInfo
  **/
  public List<MembersInfoSharesInfo> getShareParticipantInfo() {
    return shareParticipantInfo;
  }

  public void setShareParticipantInfo(List<MembersInfoSharesInfo> shareParticipantInfo) {
    this.shareParticipantInfo = shareParticipantInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyShareInfo myShareInfo = (MyShareInfo) o;
    return Objects.equals(this.mySharesInfo, myShareInfo.mySharesInfo) &&
        Objects.equals(this.shareParticipantInfo, myShareInfo.shareParticipantInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mySharesInfo, shareParticipantInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyShareInfo {\n");
    
    sb.append("    mySharesInfo: ").append(toIndentedString(mySharesInfo)).append("\n");
    sb.append("    shareParticipantInfo: ").append(toIndentedString(shareParticipantInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
