/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ParticipantSetsParticipantSetIdBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class ParticipantSetsParticipantSetIdBody {
  @JsonProperty("electronicSealId")
  private String electronicSealId = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("memberInfos")
  private List<AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos> memberInfos = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("privateMessage")
  private String privateMessage = null;

  /**
   * Role assumed by all participants in the set (signer, approver etc.). This cannot be changed as part of the PUT call.
   */
  public enum RoleEnum {
    SIGNER("SIGNER"),
    SENDER("SENDER"),
    APPROVER("APPROVER"),
    ACCEPTOR("ACCEPTOR"),
    CERTIFIED_RECIPIENT("CERTIFIED_RECIPIENT"),
    FORM_FILLER("FORM_FILLER"),
    DELEGATE_TO_SIGNER("DELEGATE_TO_SIGNER"),
    DELEGATE_TO_APPROVER("DELEGATE_TO_APPROVER"),
    DELEGATE_TO_ACCEPTOR("DELEGATE_TO_ACCEPTOR"),
    DELEGATE_TO_CERTIFIED_RECIPIENT("DELEGATE_TO_CERTIFIED_RECIPIENT"),
    DELEGATE_TO_FORM_FILLER("DELEGATE_TO_FORM_FILLER"),
    SHARE("SHARE"),
    NOTARY_SIGNER("NOTARY_SIGNER"),
    ELECTRONIC_SEALER("ELECTRONIC_SEALER");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RoleEnum fromValue(String input) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("role")
  private RoleEnum role = null;

  /**
   * The agreement status with respect to the participant set. This cannot be changed as part of the PUT call.
   */
  public enum StatusEnum {
    CANCELLED("CANCELLED"),
    COMPLETED("COMPLETED"),
    EXPIRED("EXPIRED"),
    NOT_YET_VISIBLE("NOT_YET_VISIBLE"),
    WAITING_FOR_NOTARIZATION("WAITING_FOR_NOTARIZATION"),
    WAITING_FOR_OTHERS("WAITING_FOR_OTHERS"),
    WAITING_FOR_MY_APPROVAL("WAITING_FOR_MY_APPROVAL"),
    WAITING_FOR_AUTHORING("WAITING_FOR_AUTHORING"),
    WAITING_FOR_MY_ACKNOWLEDGEMENT("WAITING_FOR_MY_ACKNOWLEDGEMENT"),
    WAITING_FOR_MY_ACCEPTANCE("WAITING_FOR_MY_ACCEPTANCE"),
    WAITING_FOR_MY_FORM_FILLING("WAITING_FOR_MY_FORM_FILLING"),
    WAITING_FOR_MY_DELEGATION("WAITING_FOR_MY_DELEGATION"),
    WAITING_FOR_MY_SIGNATURE("WAITING_FOR_MY_SIGNATURE"),
    WAITING_FOR_MY_VERIFICATION("WAITING_FOR_MY_VERIFICATION"),
    WAITING_FOR_PREFILL("WAITING_FOR_PREFILL");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  public ParticipantSetsParticipantSetIdBody electronicSealId(String electronicSealId) {
    this.electronicSealId = electronicSealId;
    return this;
  }

   /**
   * ID of the sealing credential, which can be obtained through &lt;b&gt;GET /autoseals&lt;/b&gt; call.
   * @return electronicSealId
  **/
  public String getElectronicSealId() {
    return electronicSealId;
  }

  public void setElectronicSealId(String electronicSealId) {
    this.electronicSealId = electronicSealId;
  }

  public ParticipantSetsParticipantSetIdBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the participant set. This cannot be changed as part of the PUT call.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ParticipantSetsParticipantSetIdBody memberInfos(List<AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos> memberInfos) {
    this.memberInfos = memberInfos;
    return this;
  }

  public ParticipantSetsParticipantSetIdBody addMemberInfosItem(AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos memberInfosItem) {
    if (this.memberInfos == null) {
      this.memberInfos = new ArrayList<>();
    }
    this.memberInfos.add(memberInfosItem);
    return this;
  }

   /**
   * Array of ParticipantInfo objects, containing participant-specific data (e.g. email). All participants in the array belong to the same set. Required, unless ParticipantSet has the ELECTRONIC_SEALER role
   * @return memberInfos
  **/
  public List<AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos> getMemberInfos() {
    return memberInfos;
  }

  public void setMemberInfos(List<AgreementsagreementIdmembersparticipantSetsparticipantSetIdMemberInfos> memberInfos) {
    this.memberInfos = memberInfos;
  }

  public ParticipantSetsParticipantSetIdBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of ParticipantSet (it can be empty, but needs not to be unique in a single agreement). Maximum no of characters in participant set name is restricted to 255. This cannot be changed as part of the PUT call.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ParticipantSetsParticipantSetIdBody order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Index indicating sequential signing group (specified for hybrid routing). This cannot be changed as part of the PUT call.
   * @return order
  **/
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public ParticipantSetsParticipantSetIdBody privateMessage(String privateMessage) {
    this.privateMessage = privateMessage;
    return this;
  }

   /**
   * Participant set&#x27;s private message - all participants in the set will receive the same message. This cannot be changed as part of the PUT call.
   * @return privateMessage
  **/
  public String getPrivateMessage() {
    return privateMessage;
  }

  public void setPrivateMessage(String privateMessage) {
    this.privateMessage = privateMessage;
  }

  public ParticipantSetsParticipantSetIdBody role(RoleEnum role) {
    this.role = role;
    return this;
  }

   /**
   * Role assumed by all participants in the set (signer, approver etc.). This cannot be changed as part of the PUT call.
   * @return role
  **/
  public RoleEnum getRole() {
    return role;
  }

  public void setRole(RoleEnum role) {
    this.role = role;
  }

  public ParticipantSetsParticipantSetIdBody status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The agreement status with respect to the participant set. This cannot be changed as part of the PUT call.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParticipantSetsParticipantSetIdBody participantSetsParticipantSetIdBody = (ParticipantSetsParticipantSetIdBody) o;
    return Objects.equals(this.electronicSealId, participantSetsParticipantSetIdBody.electronicSealId) &&
        Objects.equals(this.id, participantSetsParticipantSetIdBody.id) &&
        Objects.equals(this.memberInfos, participantSetsParticipantSetIdBody.memberInfos) &&
        Objects.equals(this.name, participantSetsParticipantSetIdBody.name) &&
        Objects.equals(this.order, participantSetsParticipantSetIdBody.order) &&
        Objects.equals(this.privateMessage, participantSetsParticipantSetIdBody.privateMessage) &&
        Objects.equals(this.role, participantSetsParticipantSetIdBody.role) &&
        Objects.equals(this.status, participantSetsParticipantSetIdBody.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(electronicSealId, id, memberInfos, name, order, privateMessage, role, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParticipantSetsParticipantSetIdBody {\n");
    
    sb.append("    electronicSealId: ").append(toIndentedString(electronicSealId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    memberInfos: ").append(toIndentedString(memberInfos)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    privateMessage: ").append(toIndentedString(privateMessage)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
