/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
/**
 * SenderInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class SenderInfo {
  @JsonProperty("company")
  private String company = null;

  @JsonProperty("createdDate")
  private LocalDate createdDate = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("hidden")
  private Boolean hidden = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("participantId")
  private String participantId = null;

  @JsonProperty("self")
  private Boolean self = null;

  /**
   * The agreement status with respect to the participant set. This cannot be changed as part of the PUT call.
   */
  public enum StatusEnum {
    CANCELLED("CANCELLED"),
    COMPLETED("COMPLETED"),
    EXPIRED("EXPIRED"),
    NOT_YET_VISIBLE("NOT_YET_VISIBLE"),
    WAITING_FOR_AUTHORING("WAITING_FOR_AUTHORING"),
    WAITING_FOR_MY_DELEGATION("WAITING_FOR_MY_DELEGATION"),
    WAITING_FOR_MY_ACCEPTANCE("WAITING_FOR_MY_ACCEPTANCE"),
    WAITING_FOR_MY_ACKNOWLEDGEMENT("WAITING_FOR_MY_ACKNOWLEDGEMENT"),
    WAITING_FOR_MY_APPROVAL("WAITING_FOR_MY_APPROVAL"),
    WAITING_FOR_MY_FORM_FILLING("WAITING_FOR_MY_FORM_FILLING"),
    WAITING_FOR_MY_SIGNATURE("WAITING_FOR_MY_SIGNATURE"),
    WAITING_FOR_NOTARIZATION("WAITING_FOR_NOTARIZATION"),
    WAITING_FOR_OTHERS("WAITING_FOR_OTHERS");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("userId")
  private String userId = null;

  public SenderInfo company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Company of the sender, if available.
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public SenderInfo createdDate(LocalDate createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The date when the sender was added. This will be returned as part of GET call but is ignored if passed as part of PUT call.
   * @return createdDate
  **/
  public LocalDate getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(LocalDate createdDate) {
    this.createdDate = createdDate;
  }

  public SenderInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the sender of the agreement.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public SenderInfo hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * True if the agreement is hidden for the user that is calling the API. Only returned if self is true.
   * @return hidden
  **/
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public SenderInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the sender, if available.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SenderInfo participantId(String participantId) {
    this.participantId = participantId;
    return this;
  }

   /**
   *  The unique identifier of the sender of the agreement.
   * @return participantId
  **/
  public String getParticipantId() {
    return participantId;
  }

  public void setParticipantId(String participantId) {
    this.participantId = participantId;
  }

  public SenderInfo self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * True if the sender is the same user that is calling the API.
   * @return self
  **/
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }

  public SenderInfo status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The agreement status with respect to the participant set. This cannot be changed as part of the PUT call.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SenderInfo userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The user ID of the sender. This will be returned as part of GET call but is ignored if passed as part of PUT call.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SenderInfo senderInfo = (SenderInfo) o;
    return Objects.equals(this.company, senderInfo.company) &&
        Objects.equals(this.createdDate, senderInfo.createdDate) &&
        Objects.equals(this.email, senderInfo.email) &&
        Objects.equals(this.hidden, senderInfo.hidden) &&
        Objects.equals(this.name, senderInfo.name) &&
        Objects.equals(this.participantId, senderInfo.participantId) &&
        Objects.equals(this.self, senderInfo.self) &&
        Objects.equals(this.status, senderInfo.status) &&
        Objects.equals(this.userId, senderInfo.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, createdDate, email, hidden, name, participantId, self, status, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SenderInfo {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    participantId: ").append(toIndentedString(participantId)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
