/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SendOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class SendOptions {
  /**
   * Control notification mails for agreement completion events - COMPLETED, CANCELLED, EXPIRED and REJECTED
   */
  public enum CompletionEmailsEnum {
    ALL("ALL"),
    NONE("NONE");

    private String value;

    CompletionEmailsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CompletionEmailsEnum fromValue(String input) {
      for (CompletionEmailsEnum b : CompletionEmailsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("completionEmails")
  private CompletionEmailsEnum completionEmails = null;

  /**
   * Control notification mails for agreement-in-process events - DELEGATED, REPLACED
   */
  public enum InFlightEmailsEnum {
    ALL("ALL"),
    NONE("NONE");

    private String value;

    InFlightEmailsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static InFlightEmailsEnum fromValue(String input) {
      for (InFlightEmailsEnum b : InFlightEmailsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("inFlightEmails")
  private InFlightEmailsEnum inFlightEmails = null;

  /**
   * Control notification mails for Agreement initiation events - ACTION_REQUESTED and CREATED
   */
  public enum InitEmailsEnum {
    ALL("ALL"),
    NONE("NONE");

    private String value;

    InitEmailsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static InitEmailsEnum fromValue(String input) {
      for (InitEmailsEnum b : InitEmailsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("initEmails")
  private InitEmailsEnum initEmails = null;

  public SendOptions completionEmails(CompletionEmailsEnum completionEmails) {
    this.completionEmails = completionEmails;
    return this;
  }

   /**
   * Control notification mails for agreement completion events - COMPLETED, CANCELLED, EXPIRED and REJECTED
   * @return completionEmails
  **/
  public CompletionEmailsEnum getCompletionEmails() {
    return completionEmails;
  }

  public void setCompletionEmails(CompletionEmailsEnum completionEmails) {
    this.completionEmails = completionEmails;
  }

  public SendOptions inFlightEmails(InFlightEmailsEnum inFlightEmails) {
    this.inFlightEmails = inFlightEmails;
    return this;
  }

   /**
   * Control notification mails for agreement-in-process events - DELEGATED, REPLACED
   * @return inFlightEmails
  **/
  public InFlightEmailsEnum getInFlightEmails() {
    return inFlightEmails;
  }

  public void setInFlightEmails(InFlightEmailsEnum inFlightEmails) {
    this.inFlightEmails = inFlightEmails;
  }

  public SendOptions initEmails(InitEmailsEnum initEmails) {
    this.initEmails = initEmails;
    return this;
  }

   /**
   * Control notification mails for Agreement initiation events - ACTION_REQUESTED and CREATED
   * @return initEmails
  **/
  public InitEmailsEnum getInitEmails() {
    return initEmails;
  }

  public void setInitEmails(InitEmailsEnum initEmails) {
    this.initEmails = initEmails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendOptions sendOptions = (SendOptions) o;
    return Objects.equals(this.completionEmails, sendOptions.completionEmails) &&
        Objects.equals(this.inFlightEmails, sendOptions.inFlightEmails) &&
        Objects.equals(this.initEmails, sendOptions.initEmails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completionEmails, inFlightEmails, initEmails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendOptions {\n");
    
    sb.append("    completionEmails: ").append(toIndentedString(completionEmails)).append("\n");
    sb.append("    inFlightEmails: ").append(toIndentedString(inFlightEmails)).append("\n");
    sb.append("    initEmails: ").append(toIndentedString(initEmails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
