/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShareParticipantInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class ShareParticipantInfo {
  @JsonProperty("company")
  private String company = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("hidden")
  private Boolean hidden = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("participantId")
  private String participantId = null;

  @JsonProperty("self")
  private Boolean self = null;

  @JsonProperty("sharerParticipantId")
  private String sharerParticipantId = null;

  public ShareParticipantInfo company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Company of the sharee participant, if available.
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public ShareParticipantInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the sharee participant of the agreement.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ShareParticipantInfo hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * True if the agreement is hidden for the user that is calling the API. Only returned if self is true.
   * @return hidden
  **/
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public ShareParticipantInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the sharee participant, if available.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ShareParticipantInfo participantId(String participantId) {
    this.participantId = participantId;
    return this;
  }

   /**
   * The unique identifier of the sharee participant of the agreement.
   * @return participantId
  **/
  public String getParticipantId() {
    return participantId;
  }

  public void setParticipantId(String participantId) {
    this.participantId = participantId;
  }

  public ShareParticipantInfo self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * True if the Share participant is the same user that is calling the API.
   * @return self
  **/
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }

  public ShareParticipantInfo sharerParticipantId(String sharerParticipantId) {
    this.sharerParticipantId = sharerParticipantId;
    return this;
  }

   /**
   * The unique identifier of the participant who shared the agreement.
   * @return sharerParticipantId
  **/
  public String getSharerParticipantId() {
    return sharerParticipantId;
  }

  public void setSharerParticipantId(String sharerParticipantId) {
    this.sharerParticipantId = sharerParticipantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareParticipantInfo shareParticipantInfo = (ShareParticipantInfo) o;
    return Objects.equals(this.company, shareParticipantInfo.company) &&
        Objects.equals(this.email, shareParticipantInfo.email) &&
        Objects.equals(this.hidden, shareParticipantInfo.hidden) &&
        Objects.equals(this.name, shareParticipantInfo.name) &&
        Objects.equals(this.participantId, shareParticipantInfo.participantId) &&
        Objects.equals(this.self, shareParticipantInfo.self) &&
        Objects.equals(this.sharerParticipantId, shareParticipantInfo.sharerParticipantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, email, hidden, name, participantId, self, sharerParticipantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareParticipantInfo {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    participantId: ").append(toIndentedString(participantId)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    sharerParticipantId: ").append(toIndentedString(sharerParticipantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
