/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.AgreementsagreementIdmembersshareShareCreationInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ShareCreationInfoList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class ShareCreationInfoList {
  @JsonProperty("shareCreationInfo")
  private List<AgreementsagreementIdmembersshareShareCreationInfo> shareCreationInfo = new ArrayList<>();

  public ShareCreationInfoList shareCreationInfo(List<AgreementsagreementIdmembersshareShareCreationInfo> shareCreationInfo) {
    this.shareCreationInfo = shareCreationInfo;
    return this;
  }

  public ShareCreationInfoList addShareCreationInfoItem(AgreementsagreementIdmembersshareShareCreationInfo shareCreationInfoItem) {
    this.shareCreationInfo.add(shareCreationInfoItem);
    return this;
  }

   /**
   * List of ShareCreationInfo
   * @return shareCreationInfo
  **/
  public List<AgreementsagreementIdmembersshareShareCreationInfo> getShareCreationInfo() {
    return shareCreationInfo;
  }

  public void setShareCreationInfo(List<AgreementsagreementIdmembersshareShareCreationInfo> shareCreationInfo) {
    this.shareCreationInfo = shareCreationInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareCreationInfoList shareCreationInfoList = (ShareCreationInfoList) o;
    return Objects.equals(this.shareCreationInfo, shareCreationInfoList.shareCreationInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shareCreationInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareCreationInfoList {\n");
    
    sb.append("    shareCreationInfo: ").append(toIndentedString(shareCreationInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
