/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.ShareCreationResponseListShareCreationResponseList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ShareCreationResponseList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class ShareCreationResponseList {
  @JsonProperty("shareCreationResponseList")
  private List<ShareCreationResponseListShareCreationResponseList> shareCreationResponseList = new ArrayList<>();

  public ShareCreationResponseList shareCreationResponseList(List<ShareCreationResponseListShareCreationResponseList> shareCreationResponseList) {
    this.shareCreationResponseList = shareCreationResponseList;
    return this;
  }

  public ShareCreationResponseList addShareCreationResponseListItem(ShareCreationResponseListShareCreationResponseList shareCreationResponseListItem) {
    this.shareCreationResponseList.add(shareCreationResponseListItem);
    return this;
  }

   /**
   * List of ShareCreationResponse
   * @return shareCreationResponseList
  **/
  public List<ShareCreationResponseListShareCreationResponseList> getShareCreationResponseList() {
    return shareCreationResponseList;
  }

  public void setShareCreationResponseList(List<ShareCreationResponseListShareCreationResponseList> shareCreationResponseList) {
    this.shareCreationResponseList = shareCreationResponseList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareCreationResponseList shareCreationResponseList = (ShareCreationResponseList) o;
    return Objects.equals(this.shareCreationResponseList, shareCreationResponseList.shareCreationResponseList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shareCreationResponseList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareCreationResponseList {\n");
    
    sb.append("    shareCreationResponseList: ").append(toIndentedString(shareCreationResponseList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
