/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.SigningUrlResponseSigningUrls;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * SigningUrlResponseSigningUrlSetInfos
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class SigningUrlResponseSigningUrlSetInfos {
  @JsonProperty("signingUrlSetName")
  private String signingUrlSetName = null;

  @JsonProperty("signingUrls")
  private List<SigningUrlResponseSigningUrls> signingUrls = new ArrayList<>();

  public SigningUrlResponseSigningUrlSetInfos signingUrlSetName(String signingUrlSetName) {
    this.signingUrlSetName = signingUrlSetName;
    return this;
  }

   /**
   * The name of the current signer set. Returned only, if the API caller is the sender of agreement
   * @return signingUrlSetName
  **/
  public String getSigningUrlSetName() {
    return signingUrlSetName;
  }

  public void setSigningUrlSetName(String signingUrlSetName) {
    this.signingUrlSetName = signingUrlSetName;
  }

  public SigningUrlResponseSigningUrlSetInfos signingUrls(List<SigningUrlResponseSigningUrls> signingUrls) {
    this.signingUrls = signingUrls;
    return this;
  }

  public SigningUrlResponseSigningUrlSetInfos addSigningUrlsItem(SigningUrlResponseSigningUrls signingUrlsItem) {
    this.signingUrls.add(signingUrlsItem);
    return this;
  }

   /**
   * An array of urls for current signer set.
   * @return signingUrls
  **/
  public List<SigningUrlResponseSigningUrls> getSigningUrls() {
    return signingUrls;
  }

  public void setSigningUrls(List<SigningUrlResponseSigningUrls> signingUrls) {
    this.signingUrls = signingUrls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SigningUrlResponseSigningUrlSetInfos signingUrlResponseSigningUrlSetInfos = (SigningUrlResponseSigningUrlSetInfos) o;
    return Objects.equals(this.signingUrlSetName, signingUrlResponseSigningUrlSetInfos.signingUrlSetName) &&
        Objects.equals(this.signingUrls, signingUrlResponseSigningUrlSetInfos.signingUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signingUrlSetName, signingUrls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SigningUrlResponseSigningUrlSetInfos {\n");
    
    sb.append("    signingUrlSetName: ").append(toIndentedString(signingUrlSetName)).append("\n");
    sb.append("    signingUrls: ").append(toIndentedString(signingUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
