/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SigningUrl
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class SigningUrl {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("esignUrl")
  private String esignUrl = null;

  public SigningUrl email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the signer associated with this signing url
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public SigningUrl esignUrl(String esignUrl) {
    this.esignUrl = esignUrl;
    return this;
  }

   /**
   * The email address of the signer associated with this signing url
   * @return esignUrl
  **/
  public String getEsignUrl() {
    return esignUrl;
  }

  public void setEsignUrl(String esignUrl) {
    this.esignUrl = esignUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SigningUrl signingUrl = (SigningUrl) o;
    return Objects.equals(this.email, signingUrl.email) &&
        Objects.equals(this.esignUrl, signingUrl.esignUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, esignUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SigningUrl {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    esignUrl: ").append(toIndentedString(esignUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
