/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import api.rest.v6.client.UserAgreementDisplayParticipantSetInfos;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
/**
 * UserAgreementsUserAgreementList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class UserAgreementsUserAgreementList {
  @JsonProperty("displayDate")
  private LocalDate displayDate = null;

  @JsonProperty("displayParticipantSetInfos")
  private List<UserAgreementDisplayParticipantSetInfos> displayParticipantSetInfos = new ArrayList<>();

  @JsonProperty("esign")
  private Boolean esign = null;

  @JsonProperty("groupId")
  private String groupId = null;

  @JsonProperty("hidden")
  private Boolean hidden = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("latestVersionId")
  private String latestVersionId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("parentId")
  private String parentId = null;

  /**
   * This is a server generated attribute which provides the detailed status of an agreement with respect to the apiCaller
   */
  public enum StatusEnum {
    WAITING_FOR_MY_SIGNATURE("WAITING_FOR_MY_SIGNATURE"),
    WAITING_FOR_MY_APPROVAL("WAITING_FOR_MY_APPROVAL"),
    WAITING_FOR_MY_DELEGATION("WAITING_FOR_MY_DELEGATION"),
    WAITING_FOR_MY_ACKNOWLEDGEMENT("WAITING_FOR_MY_ACKNOWLEDGEMENT"),
    WAITING_FOR_MY_ACCEPTANCE("WAITING_FOR_MY_ACCEPTANCE"),
    WAITING_FOR_MY_FORM_FILLING("WAITING_FOR_MY_FORM_FILLING"),
    WAITING_FOR_NOTARIZATION("WAITING_FOR_NOTARIZATION"),
    OUT_FOR_SIGNATURE("OUT_FOR_SIGNATURE"),
    OUT_FOR_APPROVAL("OUT_FOR_APPROVAL"),
    OUT_FOR_DELIVERY("OUT_FOR_DELIVERY"),
    OUT_FOR_ACCEPTANCE("OUT_FOR_ACCEPTANCE"),
    OUT_FOR_FORM_FILLING("OUT_FOR_FORM_FILLING"),
    SIGNED("SIGNED"),
    APPROVED("APPROVED"),
    FORM_FILLED("FORM_FILLED"),
    DELIVERED("DELIVERED"),
    ACCEPTED("ACCEPTED"),
    ARCHIVED("ARCHIVED"),
    CANCELLED("CANCELLED"),
    EXPIRED("EXPIRED"),
    WAITING_FOR_AUTHORING("WAITING_FOR_AUTHORING"),
    WAITING_FOR_PREFILL("WAITING_FOR_PREFILL"),
    DRAFT("DRAFT"),
    DOCUMENTS_NOT_YET_PROCESSED("DOCUMENTS_NOT_YET_PROCESSED"),
    WAITING_FOR_MY_VERIFICATION("WAITING_FOR_MY_VERIFICATION"),
    WAITING_FOR_VERIFICATION("WAITING_FOR_VERIFICATION");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  /**
   * The kind of agreement
   */
  public enum TypeEnum {
    AGREEMENT("AGREEMENT"),
    MEGASIGN_CHILD("MEGASIGN_CHILD"),
    WIDGET_INSTANCE("WIDGET_INSTANCE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public UserAgreementsUserAgreementList displayDate(LocalDate displayDate) {
    this.displayDate = displayDate;
    return this;
  }

   /**
   * The display date for the agreement. Format would be yyyy-MM-dd&#x27;T&#x27;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
   * @return displayDate
  **/
  public LocalDate getDisplayDate() {
    return displayDate;
  }

  public void setDisplayDate(LocalDate displayDate) {
    this.displayDate = displayDate;
  }

  public UserAgreementsUserAgreementList displayParticipantSetInfos(List<UserAgreementDisplayParticipantSetInfos> displayParticipantSetInfos) {
    this.displayParticipantSetInfos = displayParticipantSetInfos;
    return this;
  }

  public UserAgreementsUserAgreementList addDisplayParticipantSetInfosItem(UserAgreementDisplayParticipantSetInfos displayParticipantSetInfosItem) {
    this.displayParticipantSetInfos.add(displayParticipantSetInfosItem);
    return this;
  }

   /**
   * The most relevant current user set for the agreement. It is typically the next signer if the agreement is from the current user, or the sender if received from another user
   * @return displayParticipantSetInfos
  **/
  public List<UserAgreementDisplayParticipantSetInfos> getDisplayParticipantSetInfos() {
    return displayParticipantSetInfos;
  }

  public void setDisplayParticipantSetInfos(List<UserAgreementDisplayParticipantSetInfos> displayParticipantSetInfos) {
    this.displayParticipantSetInfos = displayParticipantSetInfos;
  }

  public UserAgreementsUserAgreementList esign(Boolean esign) {
    this.esign = esign;
    return this;
  }

   /**
   * True if this is an e-sign document
   * @return esign
  **/
  public Boolean isEsign() {
    return esign;
  }

  public void setEsign(Boolean esign) {
    this.esign = esign;
  }

  public UserAgreementsUserAgreementList groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Unique identifier of the group
   * @return groupId
  **/
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public UserAgreementsUserAgreementList hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * True if agreement is hidden for the user
   * @return hidden
  **/
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public UserAgreementsUserAgreementList id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the agreement.If provided in POST, it will simply be ignored
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UserAgreementsUserAgreementList latestVersionId(String latestVersionId) {
    this.latestVersionId = latestVersionId;
    return this;
  }

   /**
   * A version ID which uniquely identifies the current version of the agreement
   * @return latestVersionId
  **/
  public String getLatestVersionId() {
    return latestVersionId;
  }

  public void setLatestVersionId(String latestVersionId) {
    this.latestVersionId = latestVersionId;
  }

  public UserAgreementsUserAgreementList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the Agreement
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserAgreementsUserAgreementList parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * The parent id of a bulk send child *OR* the originating id of a web form agreement instance
   * @return parentId
  **/
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public UserAgreementsUserAgreementList status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * This is a server generated attribute which provides the detailed status of an agreement with respect to the apiCaller
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public UserAgreementsUserAgreementList type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The kind of agreement
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAgreementsUserAgreementList userAgreementsUserAgreementList = (UserAgreementsUserAgreementList) o;
    return Objects.equals(this.displayDate, userAgreementsUserAgreementList.displayDate) &&
        Objects.equals(this.displayParticipantSetInfos, userAgreementsUserAgreementList.displayParticipantSetInfos) &&
        Objects.equals(this.esign, userAgreementsUserAgreementList.esign) &&
        Objects.equals(this.groupId, userAgreementsUserAgreementList.groupId) &&
        Objects.equals(this.hidden, userAgreementsUserAgreementList.hidden) &&
        Objects.equals(this.id, userAgreementsUserAgreementList.id) &&
        Objects.equals(this.latestVersionId, userAgreementsUserAgreementList.latestVersionId) &&
        Objects.equals(this.name, userAgreementsUserAgreementList.name) &&
        Objects.equals(this.parentId, userAgreementsUserAgreementList.parentId) &&
        Objects.equals(this.status, userAgreementsUserAgreementList.status) &&
        Objects.equals(this.type, userAgreementsUserAgreementList.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayDate, displayParticipantSetInfos, esign, groupId, hidden, id, latestVersionId, name, parentId, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAgreementsUserAgreementList {\n");
    
    sb.append("    displayDate: ").append(toIndentedString(displayDate)).append("\n");
    sb.append("    displayParticipantSetInfos: ").append(toIndentedString(displayParticipantSetInfos)).append("\n");
    sb.append("    esign: ").append(toIndentedString(esign)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    latestVersionId: ").append(toIndentedString(latestVersionId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
