/*
 * secure.na1.adobesign.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package api.rest.v6.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * VaultEventInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-19T08:55:29.579198300+02:00[Europe/Vienna]")
public class VaultEventInfo {
  @JsonProperty("vaultEventComment")
  private String vaultEventComment = null;

  @JsonProperty("vaultEventId")
  private String vaultEventId = null;

  public VaultEventInfo vaultEventComment(String vaultEventComment) {
    this.vaultEventComment = vaultEventComment;
    return this;
  }

   /**
   * The description provided by the vault provider for the vault event
   * @return vaultEventComment
  **/
  public String getVaultEventComment() {
    return vaultEventComment;
  }

  public void setVaultEventComment(String vaultEventComment) {
    this.vaultEventComment = vaultEventComment;
  }

  public VaultEventInfo vaultEventId(String vaultEventId) {
    this.vaultEventId = vaultEventId;
    return this;
  }

   /**
   * The identifier assigned by the vault provider for the vault event
   * @return vaultEventId
  **/
  public String getVaultEventId() {
    return vaultEventId;
  }

  public void setVaultEventId(String vaultEventId) {
    this.vaultEventId = vaultEventId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaultEventInfo vaultEventInfo = (VaultEventInfo) o;
    return Objects.equals(this.vaultEventComment, vaultEventInfo.vaultEventComment) &&
        Objects.equals(this.vaultEventId, vaultEventInfo.vaultEventId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vaultEventComment, vaultEventId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaultEventInfo {\n");
    
    sb.append("    vaultEventComment: ").append(toIndentedString(vaultEventComment)).append("\n");
    sb.append("    vaultEventId: ").append(toIndentedString(vaultEventId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
