name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v6
    secrets:
      mvnArgs: -Dadobe.host=${{secrets.HOST}} -Dadobe.integrationKey=${{secrets.INTERRATION_KEY}} -Dadobe.returnPage=${{secrets.RETURN_PAGE}}